# Generated by Django 4.1.5 on 2024-02-22 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0002_alter_interface_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcp_ip', models.CharField(default=None, max_length=100)),
                ('protocol', models.CharField(default=None, max_length=100)),
                ('source_address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('source_port', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('destination_address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('destination_port', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('snat_type', models.CharField(default=None, max_length=10)),
                ('translation_address_from', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('translation_address_to', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('translation_port', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('rule_number', models.IntegerField(default=None, null=True)),
                ('rule_status', models.BooleanField(default=False, null=True)),
                ('interface', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='network.interface')),
            ],
            options={
                'db_table': 'nat_snat',
            },
        ),
    ]
