# Generated by Django 4.1.5 on 2024-02-23 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_interface_id'),
        ('nat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snat',
            name='rule_status',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.CreateModel(
            name='DNat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcp_ip', models.CharField(default=None, max_length=100)),
                ('protocol', models.CharField(default=None, max_length=100)),
                ('source_address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('source_port_from', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('source_port_to', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('external_address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('internal_address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('destination_port_from', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('destination_port_to', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('destination_port', models.CharField(blank=True, default=None, max_length=20, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('rule_number', models.IntegerField(default=None, null=True)),
                ('rule_status', models.BooleanField(default=True, null=True)),
                ('interface', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='network.interface')),
            ],
            options={
                'db_table': 'nat_dnat',
            },
        ),
    ]
