# Generated by Django 4.1.5 on 2024-03-04 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0003_onetoonenat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnat',
            name='protocol',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dnat',
            name='tcp_ip',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snat',
            name='protocol',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='snat',
            name='tcp_ip',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
