# Generated by Django 4.1.5 on 2025-02-19 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0007_dnat_rule_content_onetoonenat_rule_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dnat',
            old_name='dnat_position',
            new_name='db_position',
        ),
        migrations.RenameField(
            model_name='onetoonenat',
            old_name='one_to_one_nat_position',
            new_name='db_position',
        ),
        migrations.RenameField(
            model_name='snat',
            old_name='snat_position',
            new_name='db_position',
        ),
    ]
