# Generated by Django 5.2 on 2025-05-23 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0008_rename_dnat_position_dnat_db_position_and_more'),
        ('network', '0007_alter_interface_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snat',
            name='interface',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.interface'),
        ),
    ]
