# Generated by Django 5.2 on 2025-07-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0011_dnat_destination_port_forwarding_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnat',
            name='source_protocol',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
