# Generated by Django 5.2.5 on 2026-05-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('backup_id', models.CharField(max_length=100, unique=True)),
                ('backup_type', models.CharField(choices=[('safe_backup', 'Safe Backup'), ('full_backup', 'Full Backup'), ('db_backup', 'DB Backup'), ('custom', 'Custom Backup')], max_length=20)),
                ('backup_scope', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('ok', 'Success'), ('partial', 'Partial'), ('error', 'Error')], max_length=10)),
                ('health_score', models.IntegerField(blank=True, null=True)),
                ('size_mb', models.FloatField(blank=True, null=True)),
                ('components_success', models.IntegerField(default=0)),
                ('components_failed', models.IntegerField(default=0)),
                ('components_skipped', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True)),
                ('local_path', models.CharField(blank=True, max_length=500)),
                ('cloud_uploaded', models.BooleanField(default=False)),
                ('cloud_provider', models.CharField(blank=True, max_length=30)),
                ('cloud_bucket', models.CharField(blank=True, max_length=255)),
                ('cloud_key', models.CharField(blank=True, help_text='S3 object key in bucket', max_length=500)),
                ('cloud_size_mb', models.FloatField(blank=True, null=True)),
                ('cloud_uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('cloud_error', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'backup_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CloudStorageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('backblaze_b2', 'Backblaze B2'), ('cloudflare_r2', 'Cloudflare R2'), ('aws_s3', 'AWS S3'), ('minio', 'MinIO (self-hosted)'), ('custom', 'Custom S3-compatible')], default='backblaze_b2', max_length=30)),
                ('endpoint_url', models.CharField(blank=True, help_text='Leave empty for AWS S3', max_length=255)),
                ('access_key_id', models.CharField(max_length=255)),
                ('secret_access_key', models.CharField(max_length=255)),
                ('bucket_name', models.CharField(max_length=255)),
                ('region', models.CharField(default='us-east-1', max_length=50)),
                ('prefix', models.CharField(default='asguard-backups/', help_text='Folder prefix inside bucket', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('auto_upload', models.BooleanField(default=True, help_text='Auto-upload after every backup')),
                ('upload_db_only_to_cloud', models.BooleanField(default=False, help_text='DB backups go to cloud only, not kept locally')),
                ('max_cloud_copies', models.PositiveIntegerField(default=10, help_text='Max backups to keep in cloud (oldest deleted)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'backup_cloud_config',
            },
        ),
    ]
