# Generated by Django 5.2.5 on 2026-07-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackupRecord',
        ),
        migrations.DeleteModel(
            name='CloudStorageConfig',
        ),
    ]
