# Generated by Django 4.1.5 on 2025-08-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementGroup', '0002_alter_group_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='fonctionalities',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
