# Generated by Django 4.1.5 on 2023-10-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=200, null=True, unique=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('gid', models.IntegerField(null=True, unique=True)),
                ('created_by_system', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'group',
            },
        ),
    ]
