# Generated by Django 4.1.5 on 2023-10-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementGroup', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_by_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='gid',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupname',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='group',
            table='group',
        ),
    ]
