# Generated by Django 4.1.5 on 2024-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementGroup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='groupname',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='group name'),
        ),
    ]
