# Generated by Django 4.1.5 on 2023-10-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_server', models.CharField(max_length=200, null=True)),
                ('hostname', models.CharField(max_length=800, null=True)),
                ('transport', models.CharField(max_length=800, null=True)),
                ('protocol_version', models.CharField(max_length=800, null=True)),
                ('scope', models.CharField(max_length=800, null=True)),
                ('domaine_name', models.CharField(max_length=200, null=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementServers.type')),
            ],
            options={
                'db_table': 'server',
            },
        ),
    ]
