# Generated by Django 4.1.5 on 2024-03-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LdapServer', '0003_alter_adserver_server_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='adserver',
            name='server_type',
            field=models.CharField(choices=[('openldap', 'OpenLDAP Server'), ('ad', 'Active Directory Server')], default='ad', max_length=10),
        ),
    ]
