# Generated by Django 4.1.5 on 2024-10-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0005_ztnacontrollerlogs_ztnarouterlogs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identities',
            name='os',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
