# Generated by Django 4.1.5 on 2024-03-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlan', '0005_alter_vlan_vlan_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
