# Generated by Django 5.2 on 2025-05-23 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0009_alter_snat_interface'),
        ('network', '0007_alter_interface_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnat',
            name='interface',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.interface'),
        ),
        migrations.AlterField(
            model_name='onetoonenat',
            name='interface',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.interface'),
        ),
    ]
