# Generated by Django 4.2.1 on 2023-08-17 14:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gwname', models.CharField(max_length=200, null=True, unique=True)),
                ('gwaddress', models.CharField(max_length=200, null=True, unique=True)),
                ('staticgw', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200, null=True)),
                ('default_aux', models.BooleanField(default=True)),
                ('far_aux', models.BooleanField(default=False)),
                ('multiwan_aux', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'Gateway',
            },
        ),
    ]
