# Generated by Django 4.1.5 on 2023-10-27 15:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gwname', models.CharField(max_length=200, null=True, unique=True)),
                ('gwaddress', models.CharField(max_length=200, null=True)),
                ('staticgw', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=200, null=True)),
                ('default_aux', models.BooleanField(default=True)),
                ('far_aux', models.BooleanField(default=False)),
                ('multiwan_aux', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
            ],
            options={
                'db_table': 'gateway',
            },
        ),
        migrations.CreateModel(
            name='GatewayInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.IntegerField(default=0, null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'gatewayinterface',
            },
        ),
    ]
