# Generated by Django 4.1.5 on 2024-11-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
