# Generated by Django 4.1.5 on 2023-11-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_remove_gateway_created_by_remove_gateway_updated_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gateway',
            name='ipv4_gw',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gatewayinterface',
            name='ipv4_gw_interface',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterModelTable(
            name='gatewayinterface',
            table='gateway_interface',
        ),
    ]
