# Generated by Django 4.1.5 on 2024-12-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_alter_gateway_gwname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='gwaddress',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='gateway address'),
        ),
    ]
