# Generated by Django 4.1.5 on 2024-06-10 20:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipsec', '0002_rename_remote_distingushed_name_serveripsec_remote_cert'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpsecMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishetd_date', models.CharField(blank=True, max_length=200)),
                ('active_sessions', models.IntegerField(null=True)),
                ('availability', models.IntegerField(null=True)),
                ('bytes_in', models.IntegerField(null=True)),
                ('bytes_out', models.IntegerField(null=True)),
                ('availability_bytes', models.IntegerField(null=True)),
                ('packet_loss', models.IntegerField(null=True)),
                ('tunnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsec.serveripsec')),
            ],
            options={
                'db_table': 'ipsecmonitoring',
            },
        ),
    ]
