# Generated by Django 4.1.5 on 2024-06-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecmonitoring', '0002_ipsecmonitoring_total_bytes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsecmonitoring',
            name='timestamp',
            field=models.IntegerField(null=True),
        ),
    ]
