# Generated by Django 4.1.5 on 2024-06-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecmonitoring', '0003_ipsecmonitoring_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsecmonitoring',
            name='time_added',
            field=models.FloatField(null=True),
        ),
    ]
