server{
    listen 80;
    client_max_body_size 0;   # allow large backup imports/restores (no 413)
    location /ws/ {
        proxy_pass http://app:8000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_read_timeout 86400;
        proxy_redirect off;
    }

    location / {
        proxy_pass http://app:8000;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
        alias /home/app/static/;
    }

    # location /media/ {
    #     alias /home/app/web/medias/;
    # }
}
