# Generated by Django 4.1.5 on 2024-12-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_alter_gateway_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='gwname',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='gateway name'),
        ),
    ]
