# Generated by Django 4.2.7 on 2023-12-14 14:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=200, null=True)),
                ('type', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=200, null=True, unique=True)),
                ('status', models.BooleanField(default=False)),
                ('allow_by_auth', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'proxy_rules',
            },
        ),
        migrations.CreateModel(
            name='ProxyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True, unique=True)),
            ],
            options={
                'db_table': 'proxy_user',
            },
        ),
    ]
