# Generated by Django 4.2.7 on 2024-01-02 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0005_serversatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyrules',
            name='squid_conf',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='proxy.serversatus'),
        ),
        migrations.AddField(
            model_name='proxyuser',
            name='squid_conf',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='proxy.serversatus'),
        ),
    ]
