# Generated by Django 4.2.7 on 2024-01-02 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0006_proxyrules_squid_conf_proxyuser_squid_conf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serversatus',
            old_name='status',
            new_name='status_server',
        ),
        migrations.AlterModelTable(
            name='serversatus',
            table='squid_conf',
        ),
    ]
