# Generated by Django 4.1.5 on 2024-10-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0007_rename_status_serversatus_status_server_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'access_logs',
            },
        ),
        migrations.CreateModel(
            name='CacheLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'cache_logs',
            },
        ),
        migrations.CreateModel(
            name='StoreLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'store_logs',
            },
        ),
    ]
