# Generated by Django 4.2.7 on 2023-12-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0003_proxyrules_days_proxyrules_time_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proxyrules',
            old_name='tome_to',
            new_name='time_to',
        ),
    ]
