# Generated by Django 4.1.5 on 2024-12-19 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vxlan', '0006_alter_vxlan_vxlan_interface_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vxlan',
            name='vxlan_connection_uuid',
            field=models.CharField(max_length=200, unique=True, verbose_name='connection name'),
        ),
        migrations.AlterField(
            model_name='vxlan',
            name='vxlan_destination_address',
            field=models.CharField(max_length=200, verbose_name='destination address'),
        ),
        migrations.AlterField(
            model_name='vxlan',
            name='vxlan_destination_port',
            field=models.CharField(max_length=200, verbose_name='port'),
        ),
        migrations.AlterField(
            model_name='vxlan',
            name='vxlan_id',
            field=models.IntegerField(unique=True, verbose_name='vxlan id'),
        ),
        migrations.AlterField(
            model_name='vxlan',
            name='vxlan_interface_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='interface Name'),
        ),
        migrations.AlterField(
            model_name='vxlan',
            name='vxlan_source_address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='source address'),
        ),
    ]
