# Generated by Django 4.2.7 on 2023-12-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='suricatafile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_net', models.CharField(max_length=100, null=True, unique=True)),
                ('promisc', models.BooleanField(default=True)),
                ('syslog', models.CharField(max_length=100, null=True)),
                ('eve_log', models.CharField(max_length=100, null=True)),
                ('mpm_algo', models.CharField(max_length=100, null=True)),
                ('profile', models.CharField(default='medium', max_length=100, null=True)),
                ('copy_mode', models.CharField(default='none', max_length=100, null=True)),
                ('status_enabled', models.BooleanField(default=False)),
                ('interface_ids', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'suricataconfig',
            },
        ),
        migrations.CreateModel(
            name='ids_ips_rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.IntegerField(null=True, unique=True)),
                ('action', models.CharField(max_length=200, null=True)),
                ('protocol', models.TextField(blank=True, null=True)),
                ('source_ip', models.TextField(blank=True, null=True)),
                ('direction', models.TextField(blank=True, null=True)),
                ('destination_ip', models.TextField(blank=True, null=True)),
                ('msg', models.TextField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('flowbit', models.TextField(blank=True, null=True)),
                ('rev', models.IntegerField(blank=True, null=True)),
                ('rule', models.TextField(blank=True, max_length=100000, null=True)),
                ('activate_rule', models.BooleanField(default=True)),
                ('default_rule', models.BooleanField(default=True)),
                ('suricatafile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ids_ips.suricatafile')),
            ],
            options={
                'db_table': 'ids_ips_rules',
            },
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.CharField(max_length=200, null=True)),
                ('sid', models.IntegerField(null=True)),
                ('priority', models.IntegerField(null=True)),
                ('protocol', models.TextField(null=True)),
                ('src_addr', models.TextField(null=True)),
                ('src_port', models.IntegerField(null=True)),
                ('dst_addr', models.TextField(null=True)),
                ('dst_port', models.IntegerField(null=True)),
                ('alert', models.TextField(null=True, unique=True)),
                ('suricatafile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ids_ips.suricatafile')),
            ],
            options={
                'db_table': 'alerts',
            },
        ),
    ]
