# Generated by Django 4.1.5 on 2024-12-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsec', '0002_rename_remote_distingushed_name_serveripsec_remote_cert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveripsec',
            name='conn_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='tunnel name'),
        ),
    ]
