# Generated by Django 4.1.5 on 2024-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn_monitoring', '0002_vpnmonitoring_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vpnmonitoring',
            name='address_server',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='address server'),
        ),
    ]
