# Generated by Django 4.1.5 on 2024-03-07 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_system_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='time_zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='settings.timezone'),
        ),
    ]
