# Generated by Django 4.1.5 on 2024-03-06 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0003_alter_genericconfig_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerDhcp4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_dhcpv4', models.BooleanField(default=False)),
                ('subnet_addr', models.CharField(max_length=200, null=True, unique=True)),
                ('subnet_mask', models.CharField(max_length=200, null=True, unique=True)),
                ('available_range', models.CharField(max_length=200, null=True, unique=True)),
                ('range_from', models.CharField(max_length=200, null=True, unique=True)),
                ('range_to', models.CharField(max_length=200, null=True, unique=True)),
                ('dns_server', models.CharField(max_length=200, null=True, unique=True)),
                ('gateway', models.CharField(max_length=200, null=True, unique=True)),
                ('domain_name', models.CharField(max_length=200, null=True, unique=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'server_dhcp4',
            },
        ),
    ]
