# Generated by Django 4.1.5 on 2024-03-11 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_dhcp4', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdhcp4',
            name='subnet_mask',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
