# Generated by Django 5.1.4 on 2025-02-06 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoubleMask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('taux_compression', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
            ],
            options={
                'db_table': 'double_mask',
            },
        ),
    ]
