# Generated by Django 4.1.5 on 2025-01-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0009_remove_relayspolicy_semantique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identities',
            name='attribute_identitie',
            field=models.CharField(default='attribute', max_length=500),
        ),
    ]
