# Generated by Django 5.2 on 2025-09-05 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0012_alter_relays_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relayspolicy',
            name='identity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ztna.identities'),
        ),
        migrations.AlterField(
            model_name='relayspolicy',
            name='relay',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ztna.relays'),
        ),
    ]
