# Generated by Django 5.2 on 2025-09-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0013_alter_relayspolicy_identity_alter_relayspolicy_relay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relayspolicy',
            name='identity_attribute',
        ),
        migrations.RemoveField(
            model_name='relayspolicy',
            name='relay_attribute',
        ),
    ]
