# Generated by Django 4.2.1 on 2023-09-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gateway',
            table='gateway',
        ),
        migrations.AlterModelTable(
            name='gatewayinterface',
            table='gatewayinterface',
        ),
    ]
