# Generated by Django 4.1.5 on 2023-10-02 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gateway',
            table='gateway',
        ),
        migrations.AlterModelTable(
            name='gatewayinterface',
            table='gatewayinterface',
        ),
    ]
