# Generated by Django 4.1.5 on 2023-10-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_tempsexucution_interface_description_and_more'),
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='gateway',
            name='gwaddress',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='gateway',
            table='gateway',
        ),
        migrations.CreateModel(
            name='GatewayInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.IntegerField(default=0, null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'gatewayinterface',
            },
        ),
    ]
