# Generated by Django 4.2.1 on 2023-08-22 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_interface_metric'),
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GatewayInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.IntegerField(default=0, null=True)),
                ('gateway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'GatewayInterface',
            },
        ),
        migrations.AddField(
            model_name='gateway',
            name='interfaces',
            field=models.ManyToManyField(related_name='Interfaces', through='gateway.GatewayInterface', to='network.interface'),
        ),
    ]
