# Generated by Django 4.2.1 on 2023-08-22 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0002_gatewayinterface_gateway_interfaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='gateway',
            name='updated_by',
        ),
    ]
