# Generated by Django 4.2.1 on 2023-08-22 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0003_remove_gateway_created_by_remove_gateway_updated_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gateway',
            name='interfaces',
        ),
    ]
