# Generated by Django 4.2.1 on 2023-08-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0004_remove_gateway_interfaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gateway',
            name='gwaddress',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
