# Generated by Django 4.1.5 on 2023-04-26 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_organization_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='organizationId',
        ),
        migrations.RemoveField(
            model_name='paymenttransaction',
            name='planId',
        ),
        migrations.RemoveField(
            model_name='plansfeatures',
            name='planId',
        ),
        migrations.RemoveField(
            model_name='plansfeatures',
            name='plan_subsciption_usage',
        ),
        migrations.RemoveField(
            model_name='planssubscription',
            name='planId',
        ),
        migrations.RemoveField(
            model_name='plansubsciptionusage',
            name='plans_feature',
        ),
        migrations.RemoveField(
            model_name='plansubsciptionusage',
            name='plans_subscription',
        ),
        migrations.DeleteModel(
            name='organization',
        ),
        migrations.DeleteModel(
            name='paymentTransaction',
        ),
        migrations.DeleteModel(
            name='plan',
        ),
        migrations.DeleteModel(
            name='plansFeatures',
        ),
        migrations.DeleteModel(
            name='plansSubscription',
        ),
        migrations.DeleteModel(
            name='planSubsciptionUsage',
        ),
    ]
