# Generated by Django 4.1.5 on 2023-04-07 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_organization_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plansubsciptionusage',
            name='valid_until',
            field=models.DateField(null=True),
        ),
    ]
