# Generated by Django 4.1.5 on 2023-04-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planssubscription',
            name='end_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='planssubscription',
            name='start_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='plansubsciptionusage',
            name='valid_until',
            field=models.DateTimeField(),
        ),
    ]
