# Generated by Django 4.1.5 on 2023-04-26 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_planssubscription_end_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansfeatures',
            name='APIS',
            field=models.JSONField(null=True),
        ),
    ]
