# Generated by Django 4.1.5 on 2023-06-01 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_plansfeatures_apis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansfeatures',
            name='APIS',
        ),
        migrations.RemoveField(
            model_name='plansfeatures',
            name='plan_subsciption_usage',
        ),
    ]
