# Generated by Django 4.1.5 on 2023-06-01 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_remove_plansfeatures_plan_subsciption_usage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansfeatures',
            name='APIS',
        ),
    ]
