# Generated by Django 4.1.5 on 2024-02-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids_ips', '0005_remove_suricatafile_copy_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suricatainterface',
            name='threads',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
