# Generated by Django 4.1.5 on 2024-12-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids_ips', '0010_statslogs_suricatalogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suricatafile',
            name='home_net',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='service name'),
        ),
    ]
