# Generated by Django 4.2.7 on 2023-12-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=300, null=True, unique=True)),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True)),
                ('valid_until', models.DateTimeField(blank=True, default=None, null=True)),
                ('key_type', models.CharField(blank=True, default='RSA', max_length=100, null=True)),
                ('key_length', models.IntegerField(blank=True, default=2048, null=True)),
                ('digest_algorithm', models.CharField(blank=True, default='sha256', max_length=100, null=True)),
                ('lifetime', models.IntegerField(blank=True, default=None, null=True)),
                ('country_code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('common_name', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('serial', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
            options={
                'db_table': 'certificate_authority',
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=300, null=True, unique=True)),
                ('certificate_type', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('activation', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True)),
                ('valid_until', models.DateTimeField(blank=True, default=None, null=True)),
                ('key_type', models.CharField(blank=True, default='rsa', max_length=100, null=True)),
                ('key_length', models.IntegerField(blank=True, default=2048, null=True)),
                ('digest_algorithm', models.CharField(blank=True, default='sha256', max_length=100, null=True)),
                ('lifetime', models.IntegerField(blank=True, default=None, null=True)),
                ('private_key_location', models.CharField(blank=True, default='Save on this firewall', max_length=100, null=True)),
                ('country_code', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('city', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('organization', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('email', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('common_name', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('serial', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('reason_revocation', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('certificate_authority', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='managementCertificates.certificateauthority')),
            ],
            options={
                'db_table': 'certificate',
            },
        ),
    ]
