# Generated by Django 4.1.5 on 2024-02-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids_ips', '0006_alter_suricatainterface_threads'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suricatainterface',
            name='copy_mode',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
