# Generated by Django 4.1.5 on 2024-02-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sdwanrules',
            name='rule_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sdwanrules',
            name='table_id',
            field=models.IntegerField(default=1, unique=True),
        ),
        migrations.AlterField(
            model_name='sdwanrules',
            name='destination_address',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sdwanrules',
            name='health_check',
            field=models.FloatField(default=5),
        ),
        migrations.AlterField(
            model_name='sdwanrules',
            name='primary_interface',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
