# Generated by Django 4.1.5 on 2024-02-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
        ('sdwan', '0002_sdwanrules_rule_status_sdwanrules_table_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='members',
        ),
        migrations.CreateModel(
            name='AreaInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sdwan.area')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'area_interface',
            },
        ),
        migrations.AddField(
            model_name='area',
            name='members',
            field=models.ManyToManyField(through='sdwan.AreaInterface', to='network.interface'),
        ),
    ]
