# Generated by Django 5.2 on 2025-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan', '0005_alter_area_name_alter_sdwanrules_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdwanrules',
            name='health_check',
            field=models.FloatField(default=5, verbose_name='health_check'),
        ),
        migrations.AlterField(
            model_name='sdwanrules',
            name='health_check_target',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='health_check_target'),
        ),
    ]
