# Generated by Django 4.1.5 on 2023-12-18 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClamAV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logverbose', models.BooleanField()),
                ('tcpsocket', models.CharField(max_length=200)),
                ('tcpport', models.BooleanField()),
                ('maxthreads', models.CharField(max_length=200)),
                ('maxqueue', models.CharField(max_length=200)),
                ('idletimeout', models.CharField(max_length=20)),
                ('maxdirectoryrecursion', models.CharField(max_length=200)),
                ('followdirectorysymlinks', models.BooleanField()),
                ('followfilesymlinks', models.BooleanField()),
                ('disablecache', models.BooleanField()),
                ('alertbrokenexecutables', models.BooleanField()),
                ('alertencryptedarchive', models.BooleanField()),
                ('alertole2macros', models.BooleanField()),
                ('scanpe', models.BooleanField()),
                ('scanelf', models.BooleanField()),
                ('scanole2', models.BooleanField()),
                ('scanpdf', models.BooleanField()),
                ('scanxmldocs', models.BooleanField()),
                ('scanhwp3', models.BooleanField()),
                ('scanmail', models.BooleanField()),
                ('scanhtml', models.BooleanField()),
                ('scanarchive', models.BooleanField()),
                ('maxscansize', models.CharField(max_length=200)),
                ('maxfilesize', models.CharField(max_length=200)),
                ('maxrecursion', models.CharField(max_length=200)),
                ('maxfiles', models.CharField(max_length=200)),
                ('freshclamdatabasemirror', models.CharField(max_length=200)),
                ('frechclamconnectiontimeout', models.CharField(max_length=200)),
                ('proxyport', models.CharField(max_length=200)),
                ('clamd_enabled', models.BooleanField()),
                ('freshclam_enabled', models.BooleanField()),
            ],
            options={
                'db_table': 'clamav',
            },
        ),
        migrations.CreateModel(
            name='FreshclamDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('process_type', models.CharField(max_length=255)),
                ('line', models.TextField()),
                ('clamav', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clamav.clamav')),
            ],
            options={
                'db_table': 'clamav_freshclamDatabase',
            },
        ),
    ]
