# Generated by Django 4.1.5 on 2023-12-15 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clamav', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clamav',
            name='databasedirectory',
        ),
        migrations.RemoveField(
            model_name='clamav',
            name='maxpartitions',
        ),
    ]
