# Generated by Django 4.1.5 on 2024-05-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0004_alter_rule_rule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_description',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
