# Generated by Django 5.1.4 on 2025-03-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0007_alter_rule_rule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
