# Generated by Django 4.1.5 on 2023-06-09 14:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifname', models.CharField(max_length=200, null=True, unique=True)),
                ('private_aux', models.BooleanField(default=False)),
                ('bogon_aux', models.BooleanField(default=False)),
                ('service_status', models.CharField(default=None, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'db_table': 'Interface',
            },
        ),
        migrations.CreateModel(
            name='IP4Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeIP4', models.CharField(default=None, max_length=200, null=True)),
                ('typeDHCP', models.CharField(default=None, max_length=200, null=True)),
                ('ip_address', models.CharField(default=None, max_length=200, null=True)),
                ('netmask', models.IntegerField(default=None, null=True)),
                ('reject', models.CharField(default=None, max_length=200, null=True)),
                ('hostname', models.CharField(default=None, max_length=200, null=True)),
                ('alias_add', models.CharField(default=None, max_length=200, null=True)),
                ('alias_mask', models.CharField(default=None, max_length=200, null=True)),
                ('timeout', models.IntegerField(default=None, null=True)),
                ('retry', models.IntegerField(default=None, null=True)),
                ('reboot', models.IntegerField(default=None, null=True)),
                ('backoff', models.IntegerField(default=None, null=True)),
                ('select_timeout', models.IntegerField(default=None, null=True)),
                ('initial_interval', models.IntegerField(default=None, null=True)),
                ('dhcp_client', models.CharField(default=None, max_length=200, null=True)),
                ('domaine_name', models.CharField(default=None, max_length=200, null=True)),
                ('domain_server', models.CharField(default=None, max_length=200, null=True)),
                ('lease_time', models.CharField(default=None, max_length=200, null=True)),
                ('request', models.CharField(default=None, max_length=200, null=True)),
                ('require', models.CharField(default=None, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'IP4Config',
            },
        ),
        migrations.CreateModel(
            name='GenericConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtuV', models.IntegerField(null=True)),
                ('addmac', models.CharField(max_length=200, null=True)),
                ('mssV', models.IntegerField(null=True)),
                ('speed_duplex', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'GenericConfig',
            },
        ),
    ]
