# Generated by Django 4.2.1 on 2023-09-29 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip4config',
            name='addrgw',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterModelTable(
            name='genericconfig',
            table='genericonfig',
        ),
    ]
