# Generated by Django 4.1.5 on 2023-06-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip4config',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ip4config',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
    ]
