# Generated by Django 4.1.5 on 2023-07-04 14:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_ip4config_created_by_ip4config_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genericconfig',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='genericconfig',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
