# Generated by Django 4.1.5 on 2023-09-26 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_ip4config_addrgw'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genericconfig',
            table='genericonfig',
        ),
    ]
