# Generated by Django 4.1.5 on 2023-07-14 09:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_genericconfig_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP6Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeIP6', models.CharField(default=None, max_length=200, null=True)),
                ('typeDHCP6', models.CharField(default=None, max_length=200, null=True)),
                ('ip6_address', models.CharField(default=None, max_length=200, null=True)),
                ('netmask6', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'IP6Config',
            },
        ),
    ]
