# Generated by Django 4.1.5 on 2023-07-31 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_ip6config'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='name_interface',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
