# Generated by Django 4.1.5 on 2023-08-02 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_interface_name_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
