# Generated by Django 4.1.5 on 2023-08-04 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_interface_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip6config',
            name='IPv4_connectivity',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='IPv6_Prefix',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='Nlifetime',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='Nvalid_time',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='Plifetime',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='Prefix_delegation',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='Pvalid_time',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='Request_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='VLAN_priority',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='address',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='algorithm',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='authname',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='expire',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='id_assoc',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='id_assoc_pd',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='information_only',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='keyid',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='keyname',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='non_temporary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='prefix_delegation',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='prefix_hint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='protocol',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='rdm',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='request_options',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='royaume',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='script',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='secret',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip6config',
            name='send_options',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
