# Generated by Django 4.2.1 on 2023-08-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
        ('network', '0007_ip6config_ipv4_connectivity_ip6config_ipv6_prefix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempsExucution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
                ('cmd', models.CharField(max_length=200, null=True)),
                ('temps', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'tempsExucution',
            },
        ),
        migrations.AddField(
            model_name='interface',
            name='gateway',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gateway.gateway'),
        ),
        migrations.AddField(
            model_name='interface',
            name='metric',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
