# Generated by Django 4.2.1 on 2023-08-17 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_tempsexucution_interface_gateway_interface_metric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='gateway',
        ),
    ]
