# Generated by Django 4.2.1 on 2023-08-17 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_alter_tempsexucution_cmd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempsexucution',
            name='cmd',
            field=models.TextField(max_length=10000, null=True),
        ),
    ]
