# Generated by Django 4.2.1 on 2023-08-22 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_tempsexucution_cmd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interface',
            name='metric',
        ),
    ]
