# Generated by Django 4.2.1 on 2023-09-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_interface_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip4config',
            name='addrgw',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
