# Generated by Django 4.1.5 on 2023-09-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_interface_metric'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interface',
            table='interface',
        ),
    ]
