# Generated by Django 4.1.5 on 2023-09-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_remove_interface_metric'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genericconfig',
            table='genericConfig',
        ),
        migrations.AlterModelTable(
            name='interface',
            table='interface',
        ),
        migrations.AlterModelTable(
            name='ip4config',
            table='iP4Config',
        ),
        migrations.AlterModelTable(
            name='ip6config',
            table='iP6Config',
        ),
    ]
