# Generated by Django 4.1.5 on 2023-09-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_alter_interface_table'),
        ('network', '0013_ip4config_addrgw'),
    ]

    operations = [
    ]
