# Generated by Django 4.2.1 on 2023-09-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0013_ip4config_addrgw'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interface',
            table='interface',
        ),
    ]
