# Generated by Django 4.1.5 on 2023-11-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementCertificates', '0002_certificate_reason_revocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='key_type',
            field=models.CharField(blank=True, default='rsa', max_length=100, null=True),
        ),
    ]
