# Generated by Django 4.1.5 on 2024-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementCertificates', '0002_certificate_method_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateauthority',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, unique=True, verbose_name='name'),
        ),
    ]
