# Generated by Django 4.1.5 on 2023-11-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementCertificates', '0003_alter_certificate_key_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateauthority',
            name='common_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
