# Generated by Django 4.1.5 on 2023-12-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementCertificates', '0004_alter_certificateauthority_common_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_path',
        ),
        migrations.RemoveField(
            model_name='certificateauthority',
            name='certificate_path',
        ),
    ]
