# Generated by Django 4.1.5 on 2024-10-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0002_identities_hostname_relays_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicespolicy',
            name='identity_attribute',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicespolicy',
            name='service_attribute',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicesrelayspolicy',
            name='relay_attribute',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicesrelayspolicy',
            name='service_attribute',
            field=models.CharField(max_length=100),
        ),
    ]
