# Generated by Django 4.1.5 on 2025-01-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0008_alter_hostconfigs_name_alter_identities_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relayspolicy',
            name='semantique',
        ),
        migrations.RemoveField(
            model_name='servicespolicy',
            name='semantique',
        ),
        migrations.RemoveField(
            model_name='servicesrelayspolicy',
            name='semantique',
        ),
        migrations.AddField(
            model_name='relayspolicy',
            name='semantic',
            field=models.CharField(default='AllOf', max_length=10),
        ),
        migrations.AddField(
            model_name='servicespolicy',
            name='semantic',
            field=models.CharField(default='AllOf', max_length=10),
        ),
        migrations.AddField(
            model_name='servicesrelayspolicy',
            name='semantic',
            field=models.CharField(default='AllOf', max_length=10),
        ),
    ]
