# Generated by Django 4.2.7 on 2023-12-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerIPsec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conn_name', models.CharField(max_length=100, unique=True)),
                ('connection_method', models.CharField(blank=True, default='default', max_length=100, null=True)),
                ('key_exchange_version', models.CharField(blank=True, default='ike', max_length=100, null=True)),
                ('internet_protocol', models.CharField(blank=True, default='IPv4', max_length=100, null=True)),
                ('interface', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('remote_gateway', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dynamic_gateway', models.BooleanField(blank=True, default=False, null=True)),
                ('description_ph1', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('authentication_method', models.CharField(blank=True, default='Mutual PSK', max_length=100, null=True)),
                ('negotiation_mode', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('pre_shared_key', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('cert', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('remote_distingushed_name', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('local_key_pair', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('peer_key_pair', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('encryption_algorithm_ph1', models.CharField(blank=True, default='128', max_length=100, null=True)),
                ('hash_algorithm_ph1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dh_key_group', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('lifetime_ph1', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('policy', models.BooleanField(blank=True, default=True, null=True)),
                ('rekey', models.BooleanField(blank=True, default=False, null=True)),
                ('reauth', models.BooleanField(blank=True, default=False, null=True)),
                ('nat_traversal', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('mobike', models.BooleanField(blank=True, default=False, null=True)),
                ('deed_peer_detection', models.BooleanField(blank=True, default=False, null=True)),
                ('deed_peer_delay', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('deed_peer_timeout', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('deed_peer_action', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('inactivity_timeout', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('margin_time', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('rekey_fuzz', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('mode', models.CharField(blank=True, default='Tunnel IPv4', max_length=100, null=True)),
                ('description_ph2', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('local_address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('remote_address', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('type_local_network', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address_local_network', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('type_remote_network', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address_remote_network', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('protocol', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('encryption_algorithm_ph2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('hash_algorithm_ph2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('pfs_key_group', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('lifetime_ph2', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('auto_ping_host', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('manual_spd_entries', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('server_status', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'db_table': 'server_ipsec',
            },
        ),
    ]
