# Generated by Django 4.1.5 on 2024-01-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsec', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serveripsec',
            old_name='remote_distingushed_name',
            new_name='remote_cert',
        ),
    ]
