# Generated by Django 4.1.5 on 2023-11-24 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipsec', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serveripsec',
            name='my_identifier',
        ),
        migrations.RemoveField(
            model_name='serveripsec',
            name='peer_identifier',
        ),
    ]
