# Generated by Django 4.1.5 on 2023-11-30 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsec', '0002_remove_serveripsec_my_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveripsec',
            name='deed_peer_action',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveripsec',
            name='deed_peer_delay',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveripsec',
            name='deed_peer_timeout',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveripsec',
            name='dh_key_group',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveripsec',
            name='hash_algorithm_ph1',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
