# Generated by Django 5.2 on 2025-07-22 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsec', '0003_alter_serveripsec_conn_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveripsec',
            name='postrouting_rule_content',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='serveripsec',
            name='postrouting_rule_handle',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
