# Generated by Django 4.1.5 on 2023-12-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsec', '0003_alter_serveripsec_deed_peer_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveripsec',
            name='encryption_algorithm_ph2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveripsec',
            name='hash_algorithm_ph2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveripsec',
            name='lifetime_ph2',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveripsec',
            name='margin_time',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveripsec',
            name='nat_traversal',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveripsec',
            name='pfs_key_group',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveripsec',
            name='protocol',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveripsec',
            name='rekey_fuzz',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveripsec',
            name='type_local_network',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveripsec',
            name='type_remote_network',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
