# Generated by Django 4.1.5 on 2023-12-01 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsec', '0004_alter_serveripsec_encryption_algorithm_ph2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveripsec',
            name='server_status',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
