# Generated by Django 4.1.5 on 2023-09-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementServers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='server',
            table='server',
        ),
        migrations.AlterModelTable(
            name='type',
            table='type',
        ),
    ]
