# Generated by Django 4.1.5 on 2023-12-19 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids_ips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ids_ips_rule',
            name='content',
        ),
        migrations.RemoveField(
            model_name='ids_ips_rule',
            name='flowbit',
        ),
        migrations.AddField(
            model_name='alert',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
