# Generated by Django 4.1.5 on 2024-02-22 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
        ('ids_ips', '0002_remove_ids_ips_rule_content_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuricataInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threads', models.IntegerField(default=0, null=True)),
                ('cluster_id', models.IntegerField(default=0, null=True)),
                ('cluster_type', models.CharField(blank=True, max_length=100)),
                ('defrag', models.CharField(blank=True, max_length=100)),
                ('use_mmap', models.CharField(blank=True, max_length=100)),
                ('ring_size', models.IntegerField(default=0, null=True)),
                ('copy_iface', models.IntegerField(default=0, null=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
                ('suricata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ids_ips.suricatafile')),
            ],
            options={
                'db_table': 'suricata_interface',
            },
        ),
    ]
