# Generated by Django 4.1.5 on 2024-02-22 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids_ips', '0003_suricatainterface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suricatainterface',
            name='cluster_id',
            field=models.IntegerField(default=0, null=True, unique=True),
        ),
    ]
