# Generated by Django 4.1.5 on 2024-02-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids_ips', '0004_alter_suricatainterface_cluster_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suricatafile',
            name='copy_mode',
        ),
        migrations.AddField(
            model_name='suricatainterface',
            name='copy_mode',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
    ]
