# Generated by Django 4.1.5 on 2024-02-29 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ids_ips', '0008_suricatafile_mode_inline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suricatafile',
            name='interface_ids',
        ),
    ]
