# Generated by Django 4.1.5 on 2024-10-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids_ips', '0009_remove_suricatafile_interface_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatsLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'stats_logs',
            },
        ),
        migrations.CreateModel(
            name='SuricataLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'suricata_logs',
            },
        ),
    ]
