# Generated by Django 5.1.4 on 2025-03-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0008_alter_rule_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.CharField(max_length=10000, null=True)),
                ('timestamp', models.CharField(max_length=200, null=True)),
                ('rule', models.CharField(max_length=10000, null=True)),
                ('interfaces', models.CharField(max_length=200, null=True)),
                ('out_mac', models.CharField(max_length=200, null=True)),
                ('src_ip', models.CharField(max_length=200, null=True)),
                ('dst_ip', models.CharField(max_length=200, null=True)),
                ('len_trame', models.CharField(max_length=200, null=True)),
                ('TOS', models.CharField(max_length=200, null=True)),
                ('PREC', models.CharField(max_length=200, null=True)),
                ('TTL', models.CharField(max_length=200, null=True)),
                ('ID', models.CharField(max_length=200, null=True)),
                ('DF', models.CharField(max_length=200, null=True)),
                ('protocole', models.CharField(max_length=200, null=True)),
                ('src_port', models.CharField(max_length=200, null=True)),
                ('dst_port', models.CharField(max_length=200, null=True)),
                ('window_size', models.CharField(max_length=200, null=True)),
                ('RES', models.CharField(max_length=200, null=True)),
                ('ACK', models.CharField(max_length=200, null=True)),
                ('URGP', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'firewall_log',
            },
        ),
    ]
