# Generated by Django 4.1.5 on 2023-04-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='organization',
            table='organization',
        ),
        migrations.AlterModelTable(
            name='paymenttransaction',
            table='payment_transaction',
        ),
        migrations.AlterModelTable(
            name='plan',
            table='plan',
        ),
        migrations.AlterModelTable(
            name='plansfeatures',
            table='plans_features',
        ),
        migrations.AlterModelTable(
            name='planssubscription',
            table='plans_subscription',
        ),
        migrations.AlterModelTable(
            name='plansubsciptionusage',
            table='plan_subsciption_usage',
        ),
    ]
