# Generated by Django 4.1.5 on 2023-04-07 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_plansubsciptionusage_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansubsciptionusage',
            name='valid_until',
        ),
    ]
