# Generated by Django 4.1.5 on 2023-04-17 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_remove_plansubsciptionusage_valid_until'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planssubscription',
            name='planId',
        ),
        migrations.AddField(
            model_name='planssubscription',
            name='paymentTransactionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.paymenttransaction'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='organizationId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.organization'),
        ),
        migrations.AlterField(
            model_name='paymenttransaction',
            name='planId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.plan'),
        ),
    ]
