# Generated by Django 4.1.5 on 2023-04-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_remove_planssubscription_paymenttransactionid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planssubscription',
            name='planId',
        ),
        migrations.AddField(
            model_name='planssubscription',
            name='paymentTransactionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.plan'),
        ),
    ]
