# Generated by Django 4.1.5 on 2023-04-18 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_remove_planssubscription_planid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planssubscription',
            old_name='paymentTransactionId',
            new_name='planId',
        ),
    ]
