# Generated by Django 4.1.5 on 2023-04-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0008_rename_paymenttransactionid_planssubscription_planid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansfeatures',
            name='plan_subsciption_usage',
        ),
        migrations.AddField(
            model_name='planssubscription',
            name='plan_subsciption_usage',
            field=models.ManyToManyField(through='subscription.planSubsciptionUsage', to='subscription.planssubscription'),
        ),
    ]
