# Generated by Django 4.1.5 on 2023-04-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0009_remove_plansfeatures_plan_subsciption_usage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plansubsciptionusage',
            name='valid_until',
            field=models.DateField(default=0),
        ),
    ]
