# Generated by Django 4.1.5 on 2024-03-13 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_dhcp4', '0002_alter_serverdhcp4_subnet_mask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdhcp4',
            name='dns_server',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serverdhcp4',
            name='domain_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='serverdhcp4',
            name='gateway',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
