# Generated by Django 4.2.1 on 2023-10-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('cpu_percentage', models.FloatField()),
                ('memory_percentage', models.FloatField()),
            ],
            options={
                'db_table': 'dashboard',
            },
        ),
    ]
