# Generated by Django 4.1.5 on 2023-10-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, null=True, unique=True)),
                ('description', models.CharField(max_length=200, null=True, unique=True)),
                ('status_enabled', models.BooleanField(default=False)),
                ('status_started', models.BooleanField(default=False)),
                ('status_install', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'services ',
            },
        ),
        migrations.AlterModelTable(
            name='monitoringdata',
            table='monitoring_data',
        ),
    ]
