from asguard.settings import ALLOWED_HOSTS, CORS_ALLOWED_ORIGINS, GLOBAL_PATH


STRIPE_PUBLIC_KEY = "pk_test_51OVDcYKi3nwJjULPxfS2d6c6mbWGwOpsEeTADyLi8w8ZW7mMmcvcHZDYNgckyMXTnfGCER4grlGRc2KQzcK5jQJF004gmPOXWn"
STRIPE_SECRET_KEY = "sk_test_51OVDcYKi3nwJjULPyERGkOtF6VzVPDuxNsSD6jQVMmPNzBTOxOeT0v06MBlYRuQk7MVVxaKtyQEYTfLMbDIyGIbt00lLStOBqB"
STRIPE_SUCCESS_URL = f'{GLOBAL_PATH}success/'
STRIPE_CANCEL_URL = f'{GLOBAL_PATH}asguard/subscription/'
# STRIPE_SUCCESS_URL = 'http://127.0.0.1:8000/success/'
# STRIPE_CANCEL_URL = 'http//127.0.0.1:8000/asguard/subscription/'
