# Generated by Django 4.2.7 on 2023-12-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.IntegerField()),
                ('cpu_percentage', models.FloatField()),
                ('memory_percentage', models.FloatField()),
            ],
            options={
                'db_table': 'monitoring_data',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=200, null=True, unique=True)),
                ('description', models.CharField(max_length=200, null=True, unique=True)),
                ('status_enabled', models.BooleanField(default=False)),
                ('status_started', models.BooleanField(default=False)),
                ('status_install', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'services ',
            },
        ),
    ]
