# Generated by Django 4.1.5 on 2024-04-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigWaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_engine_initialization', models.CharField(blank=True, default='On', max_length=300, null=True)),
                ('access_request_bodies', models.BooleanField(default=True)),
                ('xml_request_body_parser', models.BooleanField(default=True)),
                ('json_request_body_parser', models.BooleanField(default=True)),
                ('maximum_request_body_size', models.IntegerField(blank=True, default=13107200, null=True)),
                ('request_body_size_files_excluded', models.IntegerField(blank=True, default=131072, null=True)),
                ('request_body_limit_action', models.CharField(blank=True, default='Reject', max_length=300, null=True)),
                ('maximum_parsing_depth_json', models.IntegerField(blank=True, default=512, null=True)),
                ('maximum_number_args_request', models.IntegerField(blank=True, default=1000, null=True)),
                ('pcre_match_limit', models.IntegerField(blank=True, default=1000, null=True)),
                ('pcre_match_limit_recursion', models.IntegerField(blank=True, default=1000, null=True)),
                ('response_body_access', models.BooleanField(default=True)),
                ('response_body_mimetype', models.CharField(blank=True, default='text/*', max_length=300, null=True)),
                ('response_body_limit', models.IntegerField(blank=True, default=524288, null=True)),
                ('response_body_limit_action', models.CharField(blank=True, default='ProcessPartial', max_length=300, null=True)),
            ],
            options={
                'db_table': 'config_waf',
            },
        ),
    ]
