# Generated by Django 4.1.5 on 2024-05-23 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0002_ruleswaf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationRulesWaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_policy', models.BooleanField(default=False)),
                ('rule_log', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'application_rule_waf',
            },
        ),
        migrations.CreateModel(
            name='ApplicationWaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=300, null=True, unique=True)),
                ('application_type', models.CharField(blank=True, default='ip', max_length=100, null=True)),
                ('application_value', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('rules', models.ManyToManyField(through='waf.ApplicationRulesWaf', to='waf.ruleswaf')),
            ],
            options={
                'db_table': 'application_waf',
            },
        ),
        migrations.AddField(
            model_name='applicationruleswaf',
            name='application_waf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waf.applicationwaf'),
        ),
        migrations.AddField(
            model_name='applicationruleswaf',
            name='rule_waf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waf.ruleswaf'),
        ),
    ]
