# Generated by Django 4.1.5 on 2024-06-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0003_applicationruleswaf_applicationwaf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationwaf',
            name='application_port',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='applicationwaf',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='applicationwaf',
            name='rule_geoip_id',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
