# Generated by Django 4.1.5 on 2024-06-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0004_applicationwaf_application_port_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertWaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_system_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('longitude', models.FloatField(default=None, null=True)),
                ('latitude', models.FloatField(default=None, null=True)),
                ('timestamp', models.DateTimeField(default=None, null=True)),
                ('violation_file', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('violation_id', models.IntegerField(default=None, null=True)),
                ('source', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('method', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('message', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('url', models.CharField(blank=True, default=None, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'alert_waf',
            },
        ),
    ]
