# Generated by Django 4.1.5 on 2024-06-19 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0005_alertwaf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertwaf',
            name='log_system_id',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
