# Generated by Django 4.1.5 on 2024-06-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0006_alter_alertwaf_log_system_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleswaf',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='applicationwaf',
            name='application_port',
            field=models.IntegerField(blank=True, default=None, null=True, unique=True),
        ),
    ]
