# Generated by Django 4.1.5 on 2024-06-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0007_ruleswaf_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertwaf',
            name='violation_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
