# Generated by Django 4.1.5 on 2024-07-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0008_alter_alertwaf_violation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationwaf',
            name='application_protocol',
            field=models.CharField(blank=True, default='http', max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='applicationwaf',
            name='certificate_name',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
