# Generated by Django 4.1.5 on 2024-08-28 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0009_applicationwaf_application_protocol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruleswaf',
            name='description_english',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ruleswaf',
            name='description_french',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
