# Generated by Django 4.1.5 on 2024-04-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RulesWaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=300, null=True, unique=True)),
                ('rule_status', models.BooleanField(default=True)),
                ('created', models.BooleanField(default=True)),
                ('rule_id', models.IntegerField(default=None, null=True, unique=True)),
                ('variables', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('operators', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('transformations', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('actions', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('rule_content', models.CharField(blank=True, default=None, max_length=3000, null=True)),
            ],
            options={
                'db_table': 'rules_waf',
            },
        ),
    ]
