# Generated by Django 4.1.5 on 2024-09-02 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0010_ruleswaf_description_english_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationwaf',
            name='config',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='waf.configwaf'),
        ),
    ]
