# Generated by Django 4.1.5 on 2024-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waf', '0011_applicationwaf_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationwaf',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ruleswaf',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='ruleswaf',
            name='rule_id',
            field=models.IntegerField(default=None, null=True, unique=True, verbose_name='rule id'),
        ),
    ]
