# Generated by Django 4.1.5 on 2023-02-28 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prever_IPV4_IPV6', models.BooleanField(default=False, null=True)),
                ('server_DNS', models.JSONField(null=True)),
                ('allow_server_DNS', models.BooleanField(default=False, null=True)),
                ('exclude_interfaces', models.CharField(max_length=800, null=True)),
                ('getway_failover', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'Network',
            },
        ),
        migrations.CreateModel(
            name='ServerReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circular_logs', models.BooleanField(default=False, null=True)),
                ('size_log_files', models.CharField(max_length=800, null=True)),
                ('log_firewall_default_blocks', models.CharField(max_length=800, null=True)),
                ('exclude_interfaces', models.CharField(max_length=800, null=True)),
                ('xxx', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'ServerReseau',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200, null=True)),
                ('domaine', models.CharField(max_length=200, null=True)),
                ('Time_zone', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'System',
            },
        ),
    ]
