# Generated by Django 4.1.5 on 2024-03-06 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='network',
            table='network',
        ),
        migrations.AlterModelTable(
            name='system',
            table='system',
        ),
        migrations.AlterModelTable(
            name='timezone',
            table='timezone',
        ),
    ]
