# Generated by Django 4.1.5 on 2024-03-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_network_table_alter_system_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='time_zone',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
