# Generated by Django 4.1.5 on 2024-03-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_system_time_zone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='network',
            name='gateway',
        ),
        migrations.RemoveField(
            model_name='network',
            name='server_dns',
        ),
        migrations.AddField(
            model_name='network',
            name='server_DNS',
            field=models.JSONField(null=True),
        ),
    ]
