# Generated by Django 4.1.5 on 2024-03-07 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_remove_network_gateway_remove_network_server_dns_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='network',
            old_name='server_DNS',
            new_name='server_dns',
        ),
    ]
