# Generated by Django 4.1.5 on 2025-08-21 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementCertificates', '0003_alter_certificateauthority_name'),
        ('network', '0007_alter_interface_description'),
        ('settings', '0008_alter_timezone_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_ssh', models.BooleanField(default=True)),
                ('root_login', models.BooleanField(default=True)),
                ('auth_method', models.CharField(max_length=800, null=True)),
                ('session_timeout', models.IntegerField(null=True)),
                ('protocol_http', models.BooleanField(default=True)),
                ('tcp_port', models.IntegerField()),
                ('login_message', models.BooleanField(default=True)),
                ('certificat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='managementCertificates.certificate')),
            ],
            options={
                'db_table': 'settings',
            },
        ),
        migrations.CreateModel(
            name='SettingInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_web', models.BooleanField(default=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.settings')),
            ],
            options={
                'db_table': 'setting_interface',
            },
        ),
    ]
