# Generated by Django 5.2 on 2025-08-23 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0009_settings_settinginterface'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='password_length',
            field=models.IntegerField(default=16),
        ),
    ]
