# Generated by Django 4.1.5 on 2024-03-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=800, null=True, unique=True),
        ),
    ]
