# Generated by Django 4.1.5 on 2025-02-27 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0009_alter_proxyuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyrules',
            name='rule_name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
