# Generated by Django 4.1.5 on 2024-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_rename_groupname_organization_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='features',
            field=models.CharField(max_length=800, unique=True, verbose_name='features'),
        ),
    ]
