# Generated by Django 4.1.5 on 2023-11-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='server_openvpn',
        ),
        migrations.AddField(
            model_name='clientopenvpn',
            name='server_host',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='clientopenvpn',
            name='server_port',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
