# Generated by Django 4.1.5 on 2024-01-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='topology',
        ),
    ]
