# Generated by Django 4.1.5 on 2024-02-22 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0002_remove_serveropenvpn_topology'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveropenvpn',
            name='client_management_password',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='client_management_port',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
    ]
