# Generated by Django 4.1.5 on 2023-11-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0002_remove_clientopenvpn_server_openvpn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='server_host',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='server_port',
        ),
        migrations.AddField(
            model_name='clientopenvpn',
            name='server_remote',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
