# Generated by Django 4.1.5 on 2024-10-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0003_serveropenvpn_client_management_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenVpnLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'openvpn_logs',
            },
        ),
    ]
