# Generated by Django 4.1.5 on 2023-11-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0003_remove_clientopenvpn_server_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientopenvpn',
            name='ca_name',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='clientopenvpn',
            name='cert_name',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='ca_name',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='cert_name',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='server_status',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
