# Generated by Django 4.1.5 on 2024-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0004_openvpnlogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientopenvpn',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True, verbose_name='name'),
        ),
    ]
