# Generated by Django 4.1.5 on 2023-11-23 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0004_clientopenvpn_ca_name_clientopenvpn_cert_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='interface',
        ),
    ]
