# Generated by Django 4.1.5 on 2023-11-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0005_remove_clientopenvpn_interface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='hardware_crypto',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='hardware_crypto',
        ),
    ]
