# Generated by Django 5.2 on 2025-09-03 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementCertificates', '0003_alter_certificateauthority_name'),
        ('openvpn', '0005_alter_clientopenvpn_name_alter_serveropenvpn_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientopenvpn',
            name='ca_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='managementCertificates.certificateauthority'),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='cert_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='managementCertificates.certificate'),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='ca_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='managementCertificates.certificateauthority'),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='cert_name',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='managementCertificates.certificate'),
        ),
    ]
