# Generated by Django 4.1.5 on 2023-12-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0006_remove_clientopenvpn_hardware_crypto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='cert',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='key',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='tls',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='ca',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='cert',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='key',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='tls',
        ),
    ]
