# Generated by Django 4.1.5 on 2023-10-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Network',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prever_ipv4_ipv6', models.BooleanField(default=False, null=True)),
                ('server_dns', models.CharField(max_length=800, null=True)),
                ('gateway', models.CharField(max_length=800, null=True)),
                ('allow_server_dns', models.BooleanField(default=False, null=True)),
                ('exclude_interfaces', models.CharField(max_length=800, null=True)),
                ('getway_failover', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'Network',
            },
        ),
        migrations.CreateModel(
            name='ServerReseau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circular_logs', models.BooleanField(default=False, null=True)),
                ('size_log_files', models.CharField(max_length=800, null=True)),
                ('log_firewall_default_blocks', models.CharField(max_length=800, null=True)),
                ('exclude_interfaces', models.CharField(max_length=800, null=True)),
                ('xxx', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'server_reseau',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=200, null=True)),
                ('domaine', models.CharField(max_length=200, null=True)),
                ('time_zone', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'System',
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800, null=True, unique=True)),
            ],
            options={
                'db_table': 'Timezone',
            },
        ),
    ]
