# Generated by Django 4.1.5 on 2023-10-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=800, null=True, unique=True)),
            ],
            options={
                'db_table': 'Timezone',
            },
        ),
        migrations.RenameField(
            model_name='network',
            old_name='allow_server_DNS',
            new_name='allow_server_dns',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='prever_IPV4_IPV6',
            new_name='prever_ipv4_ipv6',
        ),
        migrations.RenameField(
            model_name='system',
            old_name='Time_zone',
            new_name='time_zone',
        ),
        migrations.RemoveField(
            model_name='network',
            name='server_DNS',
        ),
        migrations.AddField(
            model_name='network',
            name='gateway',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterModelTable(
            name='serverreseau',
            table='server_reseau',
        ),
        migrations.AddField(
            model_name='network',
            name='server_dns',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
