# Generated by Django 4.1.5 on 2023-05-16 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_timezone_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GateWayInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.IntegerField(max_length=800, null=True, unique=True)),
                ('interface', models.CharField(max_length=800, null=True, unique=True)),
            ],
            options={
                'db_table': 'Gateway_Interface',
            },
        ),
    ]
