# Generated by Django 4.1.5 on 2023-05-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_gatewayinterface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewayinterface',
            name='gateway',
            field=models.IntegerField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='gatewayinterface',
            name='interface',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
