# Generated by Django 4.1.5 on 2023-05-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_alter_gatewayinterface_gateway_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatewayinterface',
            name='gateway',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
