# Generated by Django 4.1.5 on 2023-05-17 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_alter_gatewayinterface_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='network',
            name='gateway',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='network',
            name='server_DNS',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
