# Generated by Django 4.1.5 on 2023-09-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0007_network_gateway_alter_network_server_dns'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gatewayinterface',
            table='gateway_Interface',
        ),
        migrations.AlterModelTable(
            name='network',
            table='network',
        ),
        migrations.AlterModelTable(
            name='serverreseau',
            table='serverReseau',
        ),
        migrations.AlterModelTable(
            name='system',
            table='system',
        ),
        migrations.AlterModelTable(
            name='timezone',
            table='timezone',
        ),
    ]
