# Generated by Django 4.1.5 on 2025-01-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0006_dnat_dnat_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnat',
            name='rule_content',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, unique=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='onetoonenat',
            name='rule_content',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, unique=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='snat',
            name='rule_content',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, unique=True, verbose_name='Content'),
        ),
    ]
