# Generated by Django 4.1.5 on 2024-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server_dhcp4', '0003_alter_serverdhcp4_dns_server_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverdhcp4',
            name='available_range',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='available range'),
        ),
        migrations.AlterField(
            model_name='serverdhcp4',
            name='range_from',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='range from'),
        ),
        migrations.AlterField(
            model_name='serverdhcp4',
            name='range_to',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='range to'),
        ),
        migrations.AlterField(
            model_name='serverdhcp4',
            name='subnet_addr',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='subnet address'),
        ),
    ]
