# Generated by Django 4.1.5 on 2024-06-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0014_profile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo_url',
            field=models.CharField(blank=True, default='/media/profile/profile.jpg', max_length=1000, null=True),
        ),
    ]
