# Generated by Django 4.1.5 on 2024-10-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0016_roles_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
