# Generated by Django 4.1.5 on 2024-03-05 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LdapServer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adserver',
            table='ad_server',
        ),
    ]
