# Generated by Django 4.2.7 on 2023-12-14 14:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ifname', models.CharField(max_length=200, null=True, unique=True)),
                ('private_aux', models.BooleanField(default=False)),
                ('bogon_aux', models.BooleanField(default=False)),
                ('service_status', models.CharField(default=None, max_length=200, null=True)),
                ('name_interface', models.CharField(default=None, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('description', models.CharField(default=None, max_length=200, null=True)),
            ],
            options={
                'db_table': 'interface',
            },
        ),
        migrations.CreateModel(
            name='tempsExucution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
                ('cmd', models.TextField(max_length=10000, null=True)),
                ('temps', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'temps_exucution',
            },
        ),
        migrations.CreateModel(
            name='IP6Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeip6', models.CharField(default=None, max_length=200, null=True)),
                ('typedhcp6', models.CharField(default=None, max_length=200, null=True)),
                ('ip_address6', models.CharField(default=None, max_length=200, null=True)),
                ('netmask6', models.IntegerField(default=None, null=True)),
                ('request_only', models.BooleanField(default=False)),
                ('prefix_delegation_size', models.IntegerField(default=None, null=True)),
                ('prefix_hint', models.BooleanField(default=False)),
                ('ipv4_connectivity', models.BooleanField(default=False)),
                ('vlan_priority', models.CharField(default=None, max_length=200, null=True)),
                ('information_only', models.BooleanField(default=False)),
                ('send_options', models.CharField(default=None, max_length=200, null=True)),
                ('request_options', models.CharField(default=None, max_length=200, null=True)),
                ('script', models.CharField(default=None, max_length=200, null=True)),
                ('non_temporary', models.BooleanField(default=False)),
                ('id_assoc', models.CharField(default=None, max_length=200, null=True)),
                ('address', models.CharField(default=None, max_length=200, null=True)),
                ('nlifetime', models.CharField(default=None, max_length=200, null=True)),
                ('nvalid_time', models.CharField(default=None, max_length=200, null=True)),
                ('prefix_delegation', models.BooleanField(default=False)),
                ('id_assoc_pd', models.CharField(default=None, max_length=200, null=True)),
                ('ipv6_prefix', models.CharField(default=None, max_length=200, null=True)),
                ('plifetime', models.CharField(default=None, max_length=200, null=True)),
                ('pvalid_time', models.CharField(default=None, max_length=200, null=True)),
                ('authname', models.CharField(default=None, max_length=200, null=True)),
                ('protocol', models.CharField(default=None, max_length=200, null=True)),
                ('algorithm', models.CharField(default=None, max_length=200, null=True)),
                ('rdm', models.CharField(default=None, max_length=200, null=True)),
                ('keyname', models.CharField(default=None, max_length=200, null=True)),
                ('royaume', models.CharField(default=None, max_length=200, null=True)),
                ('keyid', models.CharField(default=None, max_length=200, null=True)),
                ('secret', models.CharField(default=None, max_length=200, null=True)),
                ('expire', models.CharField(default=None, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'ip6config',
            },
        ),
        migrations.CreateModel(
            name='IP4Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeip4', models.CharField(default=None, max_length=200, null=True)),
                ('typedhcp', models.CharField(default=None, max_length=200, null=True)),
                ('ip_address', models.CharField(default=None, max_length=200, null=True)),
                ('netmask', models.IntegerField(default=None, null=True)),
                ('addrgw', models.CharField(default=None, max_length=200, null=True)),
                ('reject', models.CharField(default=None, max_length=200, null=True)),
                ('hostname', models.CharField(default=None, max_length=200, null=True)),
                ('alias_add', models.CharField(default=None, max_length=200, null=True)),
                ('alias_mask', models.CharField(default=None, max_length=200, null=True)),
                ('timeout', models.IntegerField(default=None, null=True)),
                ('retry', models.IntegerField(default=None, null=True)),
                ('reboot', models.IntegerField(default=None, null=True)),
                ('backoff', models.IntegerField(default=None, null=True)),
                ('select_timeout', models.IntegerField(default=None, null=True)),
                ('initial_interval', models.IntegerField(default=None, null=True)),
                ('dhcp_client', models.CharField(default=None, max_length=200, null=True)),
                ('domain_name', models.CharField(default=None, max_length=200, null=True)),
                ('domain_server', models.CharField(default=None, max_length=200, null=True)),
                ('lease_time', models.CharField(default=None, max_length=200, null=True)),
                ('request', models.CharField(default=None, max_length=200, null=True)),
                ('require', models.CharField(default=None, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'ip4config',
            },
        ),
        migrations.CreateModel(
            name='GenericConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mtuv', models.IntegerField(null=True)),
                ('addmac', models.CharField(max_length=200, null=True)),
                ('mssv', models.IntegerField(null=True)),
                ('speed_duplex', models.CharField(max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'genericConfig',
            },
        ),
    ]
