# Generated by Django 4.1.5 on 2023-10-05 09:11

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tempsExucution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, null=True)),
                ('cmd', models.TextField(max_length=10000, null=True)),
                ('temps', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'temps_exucution',
            },
        ),
        migrations.AddField(
            model_name='interface',
            name='description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='interface',
            name='name_interface',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip4config',
            name='addrgw',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ip4config',
            name='created_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ip4config',
            name='updated_by',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='genericconfig',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='genericconfig',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, null=True),
        ),
        migrations.AlterModelTable(
            name='genericconfig',
            table='genericConfig',
        ),
        migrations.AlterModelTable(
            name='interface',
            table='interface',
        ),
        migrations.AlterModelTable(
            name='ip4config',
            table='ip4config',
        ),
        migrations.CreateModel(
            name='IP6Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeip6', models.CharField(default=None, max_length=200, null=True)),
                ('typedhcp6', models.CharField(default=None, max_length=200, null=True)),
                ('ip6_address', models.CharField(default=None, max_length=200, null=True)),
                ('netmask6', models.IntegerField(default=None, null=True)),
                ('request_only', models.BooleanField(default=False)),
                ('prefix_hint', models.BooleanField(default=False)),
                ('ipv4_connectivity', models.BooleanField(default=False)),
                ('vlan_priority', models.CharField(default=None, max_length=200, null=True)),
                ('information_only', models.BooleanField(default=False)),
                ('send_options', models.CharField(default=None, max_length=200, null=True)),
                ('request_options', models.CharField(default=None, max_length=200, null=True)),
                ('script', models.CharField(default=None, max_length=200, null=True)),
                ('non_temporary', models.BooleanField(default=False)),
                ('id_assoc', models.CharField(default=None, max_length=200, null=True)),
                ('address', models.CharField(default=None, max_length=200, null=True)),
                ('nlifetime', models.CharField(default=None, max_length=200, null=True)),
                ('nvalid_time', models.CharField(default=None, max_length=200, null=True)),
                ('prefix_delegation', models.CharField(default=None, max_length=200, null=True)),
                ('id_assoc_pd', models.CharField(default=None, max_length=200, null=True)),
                ('ipv6_prefix', models.CharField(default=None, max_length=200, null=True)),
                ('plifetime', models.CharField(default=None, max_length=200, null=True)),
                ('pvalid_time', models.CharField(default=None, max_length=200, null=True)),
                ('authname', models.CharField(default=None, max_length=200, null=True)),
                ('protocol', models.CharField(default=None, max_length=200, null=True)),
                ('algorithm', models.CharField(default=None, max_length=200, null=True)),
                ('rdm', models.CharField(default=None, max_length=200, null=True)),
                ('keyname', models.CharField(default=None, max_length=200, null=True)),
                ('royaume', models.CharField(default=None, max_length=200, null=True)),
                ('keyid', models.CharField(default=None, max_length=200, null=True)),
                ('secret', models.CharField(default=None, max_length=200, null=True)),
                ('expire', models.CharField(default=None, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('created_by', models.IntegerField(null=True)),
                ('updated_by', models.IntegerField(null=True)),
                ('interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'ip6config',
            },
        ),
    ]
