# Generated by Django 4.1.5 on 2023-11-04 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip4config',
            old_name='domaine_name',
            new_name='domain_name',
        ),
        migrations.RenameField(
            model_name='ip6config',
            old_name='ip6_address',
            new_name='ip_address6',
        ),
    ]
