# Generated by Django 4.1.5 on 2024-02-23 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
