# Generated by Django 4.1.5 on 2024-03-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_interface_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genericconfig',
            table='generic_config',
        ),
    ]
