# Generated by Django 4.1.5 on 2023-10-24 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_tempsexucution_interface_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip4config',
            old_name='domaine_name',
            new_name='domain_name',
        ),
    ]
