# Generated by Django 4.1.5 on 2023-11-01 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_domaine_name_ip4config_domain_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ip6config',
            old_name='ip6_address',
            new_name='ip_address6',
        ),
    ]
