# Generated by Django 4.1.5 on 2024-03-06 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_genericconfig_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='name_interface',
            field=models.CharField(default=None, max_length=200, null=True, unique=True),
        ),
    ]
