# Generated by Django 4.1.5 on 2023-11-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_rename_ip6_address_ip6config_ip_address6'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip6config',
            name='prefix_delegation_size',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ip6config',
            name='prefix_delegation',
            field=models.BooleanField(default=False),
        ),
    ]
