# Generated by Django 4.1.5 on 2024-03-06 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_interface_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='description',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
