# Generated by Django 4.1.5 on 2024-10-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_interface_is_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
