# Generated by Django 4.2.3 on 2023-08-24 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateAuthority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=300, null=True, unique=True)),
                ('certificate_value', models.TextField(blank=True, default=None, null=True)),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True)),
                ('valid_until', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=300, null=True, unique=True)),
                ('certificate_value', models.TextField(blank=True, default=None, null=True)),
                ('valid_from', models.DateTimeField(blank=True, default=None, null=True)),
                ('valid_until', models.DateTimeField(blank=True, default=None, null=True)),
                ('certificate_type', models.CharField(blank=True, default=None, null=True)),
                ('activation', models.BooleanField(default=True)),
                ('certificate_authority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='managementCertificates.certificateauthority')),
            ],
        ),
    ]
