# Generated by Django 4.1.5 on 2023-10-26 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementCertificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='common_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
