# Generated by Django 4.2.3 on 2023-08-24 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementCertificates', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='certificate',
            table='Certificate',
        ),
        migrations.AlterModelTable(
            name='certificateauthority',
            table='CertificateAuthority',
        ),
    ]
