# Generated by Django 4.2.3 on 2023-08-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementCertificates', '0002_alter_certificate_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='certificate_value',
        ),
        migrations.RemoveField(
            model_name='certificateauthority',
            name='certificate_value',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_path',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='certificate_path',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
