# Generated by Django 4.2.3 on 2023-08-29 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementCertificates', '0003_remove_certificate_certificate_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateauthority',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='common_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='country_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='digest_algorithm',
            field=models.CharField(blank=True, default='SHA256', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='key_length',
            field=models.IntegerField(blank=True, default=2048, null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='key_type',
            field=models.CharField(blank=True, default='RSA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='lifetime',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='organization',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
