# Generated by Django 4.2.3 on 2023-08-30 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementCertificates', '0004_certificateauthority_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificateauthority',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='common_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='country_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='digest_algorithm',
            field=models.CharField(blank=True, default='sha256', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='organization',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
