# Generated by Django 4.2.3 on 2023-08-31 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementCertificates', '0005_alter_certificateauthority_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='certificate',
            name='valid_until',
        ),
    ]
