# Generated by Django 4.2.3 on 2023-09-01 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementCertificates', '0006_remove_certificate_valid_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='common_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='country_code',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='digest_algorithm',
            field=models.CharField(blank=True, default='sha256', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='email',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='key_length',
            field=models.IntegerField(blank=True, default=2048, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='key_type',
            field=models.CharField(blank=True, default='RSA', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='lifetime',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='organization',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='private_key_location',
            field=models.CharField(blank=True, default='Save on this firewall', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='valid_from',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='valid_until',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
