# Generated by Django 4.2.3 on 2023-09-04 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementCertificates', '0007_certificate_city_certificate_common_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='certificate_authority',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='managementCertificates.certificateauthority'),
        ),
    ]
