# Generated by Django 4.1.5 on 2023-07-20 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPsecServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conn_name', models.CharField(max_length=100, unique=True)),
                ('authby', models.CharField(max_length=100)),
                ('left', models.CharField(max_length=100)),
                ('leftid', models.CharField(max_length=100)),
                ('leftsubnet', models.CharField(max_length=100)),
                ('right', models.CharField(max_length=100)),
                ('rightsubnet', models.CharField(max_length=100)),
                ('ike', models.CharField(max_length=100)),
                ('esp', models.CharField(max_length=100)),
                ('keyexchange', models.CharField(max_length=100)),
                ('keyingtries', models.CharField(max_length=100)),
                ('ikelifetime', models.CharField(max_length=100)),
                ('lifetime', models.CharField(max_length=100)),
                ('dpddelay', models.CharField(max_length=100)),
                ('dpdaction', models.CharField(max_length=100)),
                ('auto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IPsecSecrets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peer_address', models.CharField(max_length=100)),
                ('local_address', models.CharField(max_length=100)),
                ('authentication_method', models.CharField(max_length=100)),
                ('shared_secret', models.CharField(max_length=100)),
                ('server_ipsec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipsec.ipsecserver')),
            ],
        ),
    ]
