# Generated by Django 4.1.5 on 2024-05-06 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0006_rename_server_dns_network_server_dns'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=100, null=True),
        ),
    ]
