# Generated by Django 5.2 on 2025-07-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0010_alter_dnat_interface_alter_onetoonenat_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnat',
            name='destination_port_forwarding',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='dnat',
            name='destination_protocol',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='dnat',
            name='source_port',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
