# Generated by Django 4.1.5 on 2023-10-27 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'organization',
            },
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'plan',
            },
        ),
        migrations.CreateModel(
            name='plansFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.plan')),
            ],
            options={
                'db_table': 'plans_features',
            },
        ),
        migrations.CreateModel(
            name='plansSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.plan')),
            ],
            options={
                'db_table': 'plans_subscription',
            },
        ),
        migrations.CreateModel(
            name='planSubsciptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateTimeField()),
                ('plans_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.plansfeatures')),
                ('plans_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.planssubscription')),
            ],
            options={
                'db_table': 'plan_subsciption_usage',
            },
        ),
        migrations.CreateModel(
            name='paymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, null=True)),
                ('payment_link', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField(null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('subscription_type', models.CharField(max_length=200, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.organization')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.plan')),
            ],
            options={
                'db_table': 'payment_transaction',
            },
        ),
    ]
