# Generated by Django 4.1.5 on 2023-04-07 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupName', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(null=True)),
                ('currency', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='plansFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, null=True)),
                ('planId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.plan')),
            ],
        ),
        migrations.CreateModel(
            name='plansSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateField()),
                ('end_at', models.DateField()),
                ('planId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.plan')),
            ],
        ),
        migrations.CreateModel(
            name='planSubsciptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateField()),
                ('plans_feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.plansfeatures')),
                ('plans_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.planssubscription')),
            ],
        ),
        migrations.AddField(
            model_name='plansfeatures',
            name='plan_subsciption_usage',
            field=models.ManyToManyField(through='subscription.planSubsciptionUsage', to='subscription.planssubscription'),
        ),
        migrations.CreateModel(
            name='paymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=200, null=True)),
                ('paymentLink', models.CharField(max_length=200, null=True)),
                ('amount', models.FloatField(null=True)),
                ('status', models.CharField(max_length=200, null=True)),
                ('subscriptionType', models.CharField(max_length=200, null=True)),
                ('organizationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.organization')),
                ('planId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.plan')),
            ],
        ),
    ]
