# Generated by Django 4.1.5 on 2023-10-05 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plansfeatures',
            name='plan_subsciption_usage',
        ),
        migrations.AlterField(
            model_name='planssubscription',
            name='end_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='planssubscription',
            name='start_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='plansubsciptionusage',
            name='valid_until',
            field=models.DateTimeField(),
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organization',
        ),
        migrations.AlterModelTable(
            name='paymenttransaction',
            table='payment_transaction',
        ),
        migrations.AlterModelTable(
            name='plan',
            table='plan',
        ),
        migrations.AlterModelTable(
            name='plansfeatures',
            table='plans_features',
        ),
        migrations.AlterModelTable(
            name='planssubscription',
            table='plans_subscription',
        ),
        migrations.AlterModelTable(
            name='plansubsciptionusage',
            table='plan_subsciption_usage',
        ),
    ]
