# Generated by Django 4.1.5 on 2024-06-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.CharField(max_length=800)),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'features',
            },
        ),
    ]
