# Generated by Django 4.1.5 on 2023-12-04 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_plansfeatures_plan_subsciption_usage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='groupName',
            new_name='groupname',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='organizationId',
            new_name='organization',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='paymentLink',
            new_name='payment_link',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='planId',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='paymenttransaction',
            old_name='subscriptionType',
            new_name='subscription_type',
        ),
        migrations.RenameField(
            model_name='plansfeatures',
            old_name='planId',
            new_name='plan',
        ),
        migrations.RenameField(
            model_name='planssubscription',
            old_name='planId',
            new_name='plan',
        ),
    ]
