# Generated by Django 4.1.5 on 2024-06-19 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='features',
            field=models.CharField(max_length=800, unique=True),
        ),
    ]
