# Generated by Django 4.1.5 on 2024-06-19 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0003_alter_features_features'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='groupname',
            new_name='organization',
        ),
    ]
