# Generated by Django 4.1.5 on 2025-04-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0010_alter_identities_attribute_identitie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identities',
            name='token',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
