# Generated by Django 4.1.5 on 2024-04-19 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='verificationcode',
            table='verification_code',
        ),
    ]
