# Generated by Django 4.2.7 on 2023-12-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription', '0001_initial'),
        ('managementGroup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('context', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, null=True, unique=True)),
                ('password', models.CharField(max_length=800, null=True)),
                ('email', models.CharField(max_length=800, null=True)),
                ('fullname', models.CharField(max_length=800, null=True)),
                ('role', models.CharField(max_length=800, null=True)),
                ('uid', models.IntegerField(null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('token_last_expired', models.DateTimeField(null=True)),
                ('group', models.ManyToManyField(to='managementGroup.group')),
                ('organisation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.organization')),
                ('permission', models.ManyToManyField(to='managementUsers.permission')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
