# Generated by Django 4.1.5 on 2023-10-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_remove_plansfeatures_plan_subsciption_usage_and_more'),
        ('managementGroup', '0002_group_created_by_system_group_description_and_more'),
        ('managementUsers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('context', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(to='managementGroup.group'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='user',
            name='organisation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='subscription.organization'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='token_last_expired',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.ManyToManyField(to='managementUsers.permission'),
        ),
    ]
