# Generated by Django 4.1.5 on 2024-03-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LdapServer', '0003_alter_adserver_server_name'),
        ('managementUsers', '0002_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='LdapServer.adserver'),
        ),
    ]
