# Generated by Django 4.1.5 on 2024-03-11 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LdapServer', '0003_alter_adserver_server_name'),
        ('managementUsers', '0003_user_id_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='LdapServer.adserver'),
        ),
    ]
