# Generated by Django 4.1.5 on 2024-03-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0004_alter_user_id_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dn_user',
            field=models.CharField(max_length=900, null=True),
        ),
    ]
