# Generated by Django 4.1.5 on 2024-04-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0007_alter_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_enable_2FA',
            field=models.BooleanField(default=False),
        ),
    ]
