# Generated by Django 4.1.5 on 2024-04-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0011_alter_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
        migrations.AddField(
            model_name='profile',
            name='photo_url',
            field=models.CharField(blank=True, default='/media/profile.jpg', max_length=1000, null=True),
        ),
    ]
