# Generated by Django 4.1.5 on 2024-04-25 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0013_alter_profile_address_alter_profile_code_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='language',
            field=models.CharField(blank=True, default='en', max_length=100, null=True),
        ),
    ]
