# Generated by Django 4.1.5 on 2024-04-16 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VpnMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_server', models.CharField(max_length=200, null=True, unique=True)),
                ('client_active', models.IntegerField(null=True, unique=True)),
                ('capacity_server_in', models.IntegerField(null=True, unique=True)),
                ('capacity_client_out', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'db_table': 'vpnmonitoring',
            },
        ),
        migrations.CreateModel(
            name='VpnMonitoringClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200, null=True, unique=True)),
                ('login_time', models.CharField(max_length=200, null=True, unique=True)),
                ('address', models.CharField(max_length=200, null=True, unique=True)),
                ('bytes_recv', models.IntegerField(null=True, unique=True)),
                ('bytes_sent', models.IntegerField(null=True, unique=True)),
                ('total_traffic', models.IntegerField(null=True, unique=True)),
                ('location', models.CharField(max_length=200, null=True, unique=True)),
                ('traffic_distr', models.IntegerField(null=True, unique=True)),
                ('vpnmonitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openvpn_monitoring.vpnmonitoring')),
            ],
            options={
                'db_table': 'vpnmonitoring_clients',
            },
        ),
    ]
