# Generated by Django 4.2.7 on 2023-12-14 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=300, null=True, unique=True)),
                ('encryption_algorithm', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('key_size', models.CharField(blank=True, default=None, max_length=10, null=True)),
            ],
            options={
                'db_table': 'private_key',
            },
        ),
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=300, null=True, unique=True)),
                ('encryption_algorithm', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('key_size', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('finger_print', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('private_key', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='managementKeypairs.privatekey')),
            ],
            options={
                'db_table': 'public_key',
            },
        ),
    ]
