# Generated by Django 4.1.5 on 2023-11-22 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('managementKeypairs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='private_key',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='managementKeypairs.privatekey'),
        ),
    ]
