# Generated by Django 4.1.5 on 2023-12-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementKeypairs', '0002_alter_publickey_private_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatekey',
            name='private_key_path',
        ),
        migrations.RemoveField(
            model_name='publickey',
            name='public_key_path',
        ),
    ]
