# Generated by Django 4.1.5 on 2024-06-18 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=200)),
                ('process', models.CharField(blank=True, max_length=200)),
                ('message', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'logs_data',
            },
        ),
    ]
