# Generated by Django 4.1.5 on 2024-09-27 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HostConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_host', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('protocol', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('date_creation', models.DateTimeField()),
                ('description', models.CharField(max_length=800, null=True)),
            ],
            options={
                'db_table': 'hostconfigs',
            },
        ),
        migrations.CreateModel(
            name='Identities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_identitie', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('attribute_identitie', models.CharField(blank=True, max_length=500, null=True)),
                ('type', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=800, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField()),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('token', models.CharField(blank=True, max_length=1000, null=True, unique=True)),
            ],
            options={
                'db_table': 'identities',
            },
        ),
        migrations.CreateModel(
            name='InterceptConfigs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_intercept', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('protocol', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('low', models.IntegerField()),
                ('high', models.IntegerField()),
                ('date_creation', models.DateTimeField()),
                ('description', models.CharField(max_length=800, null=True)),
            ],
            options={
                'db_table': 'interceptconfigs',
            },
        ),
        migrations.CreateModel(
            name='Relays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_relay', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('attribute_relay', models.CharField(blank=True, max_length=500, null=True)),
                ('tunneler', models.BooleanField(default=False)),
                ('traversal', models.BooleanField(default=False)),
                ('online', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField()),
                ('description', models.CharField(max_length=800, null=True)),
            ],
            options={
                'db_table': 'relays',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_service', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('attribute_service', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.CharField(max_length=800, null=True)),
                ('encryption', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField()),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ztna.hostconfigs')),
                ('intercept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ztna.interceptconfigs')),
            ],
            options={
                'db_table': 'servicesztna',
            },
        ),
        migrations.CreateModel(
            name='ServicesPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_service_policy', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('semantique', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=800, null=True)),
                ('service_attribute', models.CharField(max_length=10)),
                ('identity_attribute', models.CharField(max_length=10)),
                ('date_creation', models.DateTimeField()),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ztna.identities')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ztna.services')),
            ],
            options={
                'db_table': 'servicepolicies',
            },
        ),
        migrations.CreateModel(
            name='RelaysPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_relay_policy', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('semantique', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=800, null=True)),
                ('identity_attribute', models.CharField(blank=True, max_length=500, null=True)),
                ('relay_attribute', models.CharField(blank=True, max_length=500, null=True)),
                ('date_creation', models.DateTimeField()),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ztna.identities')),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ztna.relays')),
            ],
            options={
                'db_table': 'relaypolicy',
            },
        ),
        migrations.CreateModel(
            name='Enrollements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('type', models.CharField(max_length=100)),
                ('identitie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ztna.identities')),
            ],
            options={
                'db_table': 'enrollements',
            },
        ),
    ]
