# Generated by Django 4.1.5 on 2024-09-27 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicesRelaysPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_service_relay_policy', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('semantique', models.CharField(max_length=10)),
                ('type', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=800, null=True)),
                ('service_attribute', models.CharField(max_length=10)),
                ('relay_attribute', models.CharField(max_length=10)),
                ('date_creation', models.DateTimeField()),
                ('relay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ztna.identities')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ztna.services')),
            ],
            options={
                'db_table': 'servicerelaypolicies',
            },
        ),
    ]
