# Generated by Django 4.1.5 on 2024-10-04 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='identities',
            name='hostname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='relays',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='identities',
            name='token',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
