# Generated by Django 4.1.5 on 2024-09-27 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0002_servicesrelayspolicy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicesrelayspolicy',
            name='type',
        ),
    ]
