# Generated by Django 4.1.5 on 2024-10-07 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0003_alter_servicespolicy_identity_attribute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identities',
            name='is_admin',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
