# Generated by Django 4.1.5 on 2024-10-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0004_alter_identities_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZtnaControllerLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'ztna_controller_logs',
            },
        ),
        migrations.CreateModel(
            name='ZtnaRouterLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=100)),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'ztna_router_logs',
            },
        ),
        migrations.AlterField(
            model_name='hostconfigs',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='identities',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='identities',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='interceptconfigs',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='relays',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='relayspolicy',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='services',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='servicespolicy',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
        migrations.AlterField(
            model_name='servicesrelayspolicy',
            name='description',
            field=models.CharField(blank=True, max_length=800, null=True),
        ),
    ]
