# Generated by Django 4.1.5 on 2024-10-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0004_alter_identities_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZtnaControllerLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'ztna_controller_logs',
            },
        ),
        migrations.CreateModel(
            name='ZtnaRouterLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=100)),
                ('log', models.TextField()),
            ],
            options={
                'db_table': 'ztna_router_logs',
            },
        ),
        migrations.AlterField(
            model_name='identities',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
