# Generated by Django 4.1.5 on 2024-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0007_alter_hostconfigs_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostconfigs',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='identities',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='interceptconfigs',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='relays',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='relayspolicy',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='services',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='servicespolicy',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='servicesrelayspolicy',
            name='name',
            field=models.CharField(max_length=500, unique=True, verbose_name='name'),
        ),
    ]
