# Generated by Django 5.2 on 2025-05-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ztna', '0011_alter_identities_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relays',
            name='token',
            field=models.CharField(blank=True, max_length=10000, null=True, unique=True),
        ),
    ]
