# Generated by Django 4.1.5 on 2023-12-27 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_description',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
