# Generated by Django 4.1.5 on 2024-04-25 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_alter_rule_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_description',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
