# Generated by Django 5.1.4 on 2025-05-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0010_alter_firewalllog_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='rule',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
