# Generated by Django 4.1.5 on 2024-12-19 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_alter_rule_rule_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_description',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='description'),
        ),
    ]
