# Generated by Django 5.1.4 on 2025-02-06 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('double_mask', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doublemask',
            name='taux_compression',
            field=models.FloatField(default=0),
        ),
    ]
