# Generated by Django 5.1.4 on 2025-02-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('double_mask', '0002_alter_doublemask_taux_compression'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doublemask',
            old_name='taux_compression',
            new_name='ratio',
        ),
    ]
