# Generated by Django 4.1.5 on 2024-02-23 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_alter_interface_id'),
        ('nat', '0002_alter_snat_rule_status_dnat'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneToOneNat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('translation_address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('destination_address', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('rule_number', models.IntegerField(default=None, null=True)),
                ('rule_status', models.BooleanField(default=True, null=True)),
                ('interface', models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='network.interface')),
            ],
            options={
                'db_table': 'nat_one_to_one',
            },
        ),
    ]
