# Generated by Django 4.1.5 on 2024-03-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LdapServer', '0002_alter_adserver_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adserver',
            name='server_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
