# Generated by Django 4.1.5 on 2024-03-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LdapServer', '0004_adserver_server_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adserver',
            name='server_type',
            field=models.CharField(choices=[('openldap', 'OpenLDAP Server'), ('ad', 'Active Directory Server')], default='openldap', max_length=10),
        ),
    ]
