# Generated by Django 4.1.5 on 2024-04-17 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vpnmonitoring',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='vpnmonitoringclient',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='vpnmonitoring',
            name='capacity_client_out',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vpnmonitoring',
            name='capacity_server_in',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vpnmonitoring',
            name='client_active',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vpnmonitoringclient',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vpnmonitoringclient',
            name='bytes_recv',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vpnmonitoringclient',
            name='bytes_sent',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vpnmonitoringclient',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vpnmonitoringclient',
            name='login_time',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='vpnmonitoringclient',
            name='total_traffic',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='vpnmonitoringclient',
            name='traffic_distr',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='vpnmonitoringclient',
            name='username',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
