# Generated by Django 4.1.5 on 2024-02-11 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
        ('sdwan', '0003_remove_area_members_areainterface_area_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdwanrules',
            name='primary_interface',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.interface'),
        ),
    ]
