# Generated by Django 5.2 on 2025-07-31 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdwan', '0006_alter_sdwanrules_health_check_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='area',
            options={'verbose_name': 'Area', 'verbose_name_plural': 'Areas'},
        ),
        migrations.AlterModelOptions(
            name='sdwanrules',
            options={'verbose_name': 'SD-WAN Rule', 'verbose_name_plural': 'SD-WAN Rules'},
        ),
    ]
