# Generated by Django 4.1.5 on 2023-12-19 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementCertificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='method_name',
            field=models.CharField(default='create', max_length=300),
        ),
        migrations.AddField(
            model_name='certificateauthority',
            name='method_name',
            field=models.CharField(default='create', max_length=300),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='digest_algorithm',
            field=models.CharField(blank=True, default='sha256', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='key_type',
            field=models.CharField(blank=True, default='rsa', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='private_key_location',
            field=models.CharField(blank=True, default='Save on this firewall', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='digest_algorithm',
            field=models.CharField(blank=True, default='sha256', max_length=100),
        ),
        migrations.AlterField(
            model_name='certificateauthority',
            name='key_type',
            field=models.CharField(blank=True, default='RSA', max_length=100),
        ),
    ]
