"""
Django settings for dms project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import subprocess
from dotenv import load_dotenv
from pathlib import Path
import os
import mimetypes
import socket
mimetypes.add_type("text/css", ".css", True)
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'mmj@uz23n!%6u4#$b1&%f(7l*rr(9qx%am)wyk@s4ugeuam52m'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']
##function to run command 
def run_command(command):
    completed_process = subprocess.run(command, shell=True, capture_output=True, text=True)
    output = completed_process.stdout
    error = completed_process.stderr
    return output, error
##function to get all addresses to be CSRF_TRUSTED_ORIGINS
def get_all_addresses():
    all_addresses=[]
    cmd="sudo cat /etc/ConfigInterfaces"
    output,error=run_command(cmd)  
    if error=="" and len(output)!=0:
        output=output.strip().split('\n')
        for a in output:
            ifname=a.split(":")[0]
            cmd_address="sudo ip a show dev {} | grep 'inet ' | cut -d ' ' -f 6".format(ifname)
            output_list,error=run_command(cmd_address)
            list_addr=[]
            if len(output_list)!=0:
                list_addr=output_list.strip().split("\n")
                for output_addr in list_addr:
                    all_addresses.append("https://"+output_addr.strip('\n').strip().split("/")[0])
    return all_addresses

##appel function to update CSRF_TRUSTED_ORIGINS
CSRF_TRUSTED_ORIGINS=get_all_addresses()
CORS_ALLOWED_ORIGINS = get_all_addresses()
# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'encore',
    'tasks',
    'rest_framework',
    'corsheaders',
    'managementUsers',
    'managementGroup',
    "managementServers",
    "settings",
    "authentification",
    "subscription",
    "network",
    "openvpn",
    "ipsec",
    "rules",
    "gateway",
    "dashboard",
    'channels',
]
# Configure the channel layer for WebSocket communication
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",  # You can use other backends as needed
    },
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",  # Here
]

ROOT_URLCONF = 'dms.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['views/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

ASGI_APPLICATION = 'dms.asgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'PASSWORD': 'mypassword',
        'HOST': 'localhost',
        'PORT': 5432,
        # 'ATOMIC_REQUESTS': True,
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# STATIC_ROOT = os.path.join(BASE_DIR, 'static')

# STATICFILES_DIRS = [
#        os.path.join(BASE_DIR, 'static'),
# ]
if DEBUG:
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static')
    ]
else:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
ENCORE_ENTRYPOINTS_FILE = os.path.join(
    BASE_DIR, 'static') + '/entrypoints.json'
# ENCORE_ENTRYPOINTS_FILE= '/home/oussema/Documents/numeryx/newdms/dms/public/build/entrypoints.json'

ENCRYPT_KEY = "57-xmiMq0yop7uD7Aq3j4PNUOgZhradICh2BKBnIdB0="
# custom user model
AUTH_USER_MODEL = "managementUsers.User"
# REST FRAMEWORK
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

# jwt_auth/settings.py
SESSION_COOKIE_AGE = 600
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_SECURE= True
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SAMESITE= 'Strict'
## add this code so that logout work with jwt and timeleft
# JWT_CONF = {
#     'TOKEN_LIFETIME_HOURS': 72,
#     'REFRESH_TOKEN_LIFETIME': 15,
#     'ROTATE_REFRESH_TOKENS': True,
#     'BLACKLIST_AFTER_ROTATION': True,
#     'JWT_AUTH_HEADER_PREFIX': 'Bearer'

# }
## end code

# Load environment variables from .env file
load_dotenv()

# SSH settings
SSH_HOST = os.getenv('SSH_HOST')
SSH_PORT = int(os.getenv('SSH_PORT'))
ASGUARD_VERSION = os.getenv('ASGUARD_VERSION')

USERNAME=None
PASSWORD=None