# Generated by Django 4.1.5 on 2024-05-23 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0005_alter_interface_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vxlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vxlan_interface_name', models.CharField(max_length=200, unique=True)),
                ('vxlan_id', models.IntegerField(unique=True)),
                ('vxlan_source_address', models.CharField(max_length=200, null=True)),
                ('vxlan_destination_address', models.CharField(max_length=200)),
                ('vxlan_destination_port', models.CharField(max_length=200, null=True)),
                ('vxlan_connection_uuid', models.CharField(max_length=200)),
                ('parent_interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'vxlan',
            },
        ),
    ]
