# Generated by Django 4.1.5 on 2024-05-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vxlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vxlan',
            name='vxlan_source_address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
