# Generated by Django 4.1.5 on 2024-05-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vxlan', '0002_alter_vxlan_vxlan_source_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vxlan',
            name='vxlan_destination_port',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
