# Generated by Django 4.1.5 on 2024-05-28 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vxlan', '0003_alter_vxlan_vxlan_destination_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vxlan',
            name='vxlan_connection_uuid',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
