# Generated by Django 4.1.5 on 2024-12-19 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vxlan', '0004_alter_vxlan_vxlan_connection_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vxlan',
            name='vxlan_interface_name',
            field=models.CharField(max_length=200, unique=True, verbose_name='VxLAN Interface Name'),
        ),
    ]
