# Generated by Django 4.1.5 on 2024-02-22 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ADServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_name', models.CharField(max_length=255)),
                ('server_url', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=389)),
                ('search_base', models.CharField(max_length=255)),
                ('bind_user_dn', models.CharField(max_length=255)),
                ('bind_user_password', models.CharField(max_length=255)),
                ('ssl_tls_activation', models.BooleanField(default=False)),
            ],
        ),
    ]
