# Generated by Django 4.1.5 on 2024-12-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LdapServer', '0005_alter_adserver_server_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adserver',
            name='server_name',
            field=models.CharField(max_length=255, unique=True, verbose_name='server name'),
        ),
    ]
