# Generated by Django 4.1.5 on 2025-09-09 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0010_settings_password_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='settings',
            name='protocol_http',
        ),
    ]
