from django.db import models

# Create your models here.

class ServerOpenvpn(models.Model):
    port = models.CharField(max_length=10,default=None,null=True,blank=True)
    proto = models.CharField(max_length=10,default=None,null=True,blank=True)
    dev = models.CharField(max_length=10,default=None,null=True,blank=True)
    user = models.CharField(max_length=100,default=None,null=True,blank=True)
    group = models.CharField(max_length=100,default=None,null=True,blank=True)
    persist_key = models.CharField(max_length=100,default=None,null=True,blank=True)
    persist_tun = models.CharField(max_length=100,default=None,null=True,blank=True)
    keepalive = models.CharField(max_length=100,default=None,null=True,blank=True)
    topology = models.CharField(max_length=100,default=None,null=True,blank=True)
    server = models.CharField(max_length=100,default=None,null=True,blank=True)
    ifconfig_pool_persist = models.CharField(max_length=100,default=None,null=True,blank=True)
    push_ipv4_option1 = models.CharField(max_length=100,default=None,null=True,blank=True)
    push_ipv4_option2 = models.CharField(max_length=100,default=None,null=True,blank=True)
    push_ipv4_option3 = models.CharField(max_length=100,default=None,null=True,blank=True)
    server_ipv6 = models.CharField(max_length=255,default=None,null=True,blank=True)
    tun_ipv6 = models.CharField(max_length=255,default=None,null=True,blank=True)
    push_ipv6_option1 = models.CharField(max_length=100,default=None,null=True,blank=True)
    push_ipv6_option2 = models.CharField(max_length=100,default=None,null=True,blank=True)
    push_ipv6_option3 = models.CharField(max_length=100,default=None,null=True,blank=True)
    dh = models.CharField(max_length=100,default=None,null=True,blank=True)
    ecdh_curve = models.CharField(max_length=100,default=None,null=True,blank=True)
    tls_crypt = models.CharField(max_length=100,default=None,null=True,blank=True)
    crl_verify = models.CharField(max_length=100,default=None,null=True,blank=True)
    ca = models.CharField(max_length=100,default=None,null=True,blank=True)
    cert = models.CharField(max_length=100,default=None,null=True,blank=True)
    key = models.CharField(max_length=100,default=None,null=True,blank=True)
    auth = models.CharField(max_length=100, default=None,null=True,blank=True)
    cipher = models.CharField(max_length=100,default=None,null=True,blank=True)
    ncp_ciphers = models.CharField(max_length=100,default=None,null=True,blank=True)
    tls_server = models.CharField(max_length=100,default=None,null=True,blank=True)
    tls_version_min = models.CharField(max_length=100,default=None,null=True,blank=True)
    tls_cipher = models.CharField(max_length=100,default=None,null=True,blank=True)
    client_config_dir = models.CharField(max_length=100,default=None,null=True,blank=True)
    status = models.CharField(max_length=100,default=None,null=True,blank=True)
    verb = models.CharField(max_length=100,default=None,null=True,blank=True)


class ClientOpenvpn(models.Model):
    serverOpenvpn = models.ForeignKey(ServerOpenvpn, on_delete=models.CASCADE,default=None)
    client = models.CharField(max_length=255,default=None)
    proto = models.CharField(max_length=10,default=None)
    explicit_exit_notify = models.CharField(max_length=100,default=None)
    remote = models.CharField(max_length=100,default=None)
    dev = models.CharField(max_length=10,default=None)
    resolv_retry = models.CharField(max_length=100,default=None)
    nobind = models.CharField(max_length=100,default=None)
    persist_key = models.CharField(max_length=100,default=None)
    persist_tun = models.CharField(max_length=100,default=None)
    remote_cert_tls = models.CharField(max_length=100,default=None)
    verify_x509_name = models.CharField(max_length=100,default=None)
    auth = models.CharField(max_length=100,default=None)
    auth_nocache = models.CharField(max_length=100,default=None)
    cipher = models.CharField(max_length=100,default=None)
    tls_client = models.CharField(max_length=100,default=None)
    tls_version_min = models.IntegerField(default=0)
    tls_cipher = models.CharField(max_length=100,default=None)
    ignore_unknown_option = models.CharField(max_length=100,default=None)
    setenv = models.CharField(max_length=100,default=None)
    verb = models.CharField(max_length=100,default=None)
    ca_certificate = models.TextField(default=None, blank=True)
    cert_certificate = models.TextField(default=None, blank=True)
    private_key = models.TextField(default=None, blank=True)
    tls_crypt = models.TextField(default=None, blank=True)