# Generated by Django 5.1.4 on 2025-03-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0009_firewalllog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewalllog',
            name='log',
            field=models.CharField(max_length=10000, null=True, unique=True),
        ),
    ]
