# Generated by Django 4.1.5 on 2024-03-05 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network', '0003_alter_genericconfig_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vlan_tag', models.IntegerField(null=True)),
                ('vlan_priority', models.IntegerField(null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('parent_interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'vlan',
            },
        ),
    ]
