# Generated by Django 4.1.5 on 2024-03-04 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0004_alter_dnat_protocol_alter_dnat_tcp_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnat',
            name='prerouting_position',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='onetoonenat',
            name='postrouting_position',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='snat',
            name='postrouting_position',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
