# Generated by Django 4.2.3 on 2023-10-06 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerOpenvpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True, unique=True)),
                ('description', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('server_mode', models.CharField(blank=True, default='remote_access', max_length=100, null=True)),
                ('proto', models.CharField(blank=True, default='udp', max_length=10, null=True)),
                ('dev', models.CharField(blank=True, default='tun', max_length=10, null=True)),
                ('interface', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('port', models.CharField(blank=True, default='1194', max_length=10, null=True, unique=True)),
                ('tls', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('ca', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('cert', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('key', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('dh', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('cipher', models.CharField(blank=True, default='AES-256-CBC', max_length=100, null=True)),
                ('auth', models.CharField(blank=True, default='SHA256', max_length=100, null=True)),
                ('hardware_crypto', models.CharField(blank=True, default='No Hardware Crypto', max_length=100, null=True)),
                ('gateway', models.BooleanField(blank=True, default=True, null=True)),
                ('ipv4_tunnel_network', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('bridge_interface', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bridge_start_dhcp', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('bridge_end_dhcp', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('ipv4_local_network', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('ipv4_remote_network', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('concurrent_connections', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('compression', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('type_of_service', models.BooleanField(blank=True, default=False, null=True)),
                ('duplicate_connections', models.BooleanField(blank=True, default=True, null=True)),
                ('ipv6', models.BooleanField(blank=True, default=False, null=True)),
                ('inter_clients', models.BooleanField(blank=True, default=False, null=True)),
                ('dynamic_ip', models.BooleanField(blank=True, default=False, null=True)),
                ('address_pool_start', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('address_pool_end', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('topology', models.BooleanField(blank=True, default=True, null=True)),
                ('dns_default_domain_server', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('dns_server1', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('dns_server2', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('force_dns_cache_update', models.BooleanField(blank=True, default=False, null=True)),
                ('ntp_server1', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('ntp_server2', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('verb', models.CharField(blank=True, default='3', max_length=100, null=True)),
            ],
            options={
                'db_table': 'server_openvpn',
            },
        ),
        migrations.CreateModel(
            name='ClientOpenvpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True)),
                ('description', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('server_mode', models.CharField(blank=True, default='peer-to-peer', max_length=100, null=True)),
                ('proto', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('dev', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('interface', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('resolv_retry', models.BooleanField(blank=True, default=False, null=True)),
                ('proxy_host', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('proxy_port', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('proxy_authentication_option', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('proxy_auth_username', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('proxy_auth_password', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('port', models.CharField(blank=True, default='1194', max_length=10, null=True)),
                ('username', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('renegotiate_time', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('tls', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('ca', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('cert', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('key', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('cipher', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('auth', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('hardware_crypto', models.CharField(blank=True, default='No Hardware Crypto', max_length=100, null=True)),
                ('ipv4_tunnel_network', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('ipv4_remote_network', models.CharField(blank=True, default=None, max_length=300, null=True)),
                ('limit_outgoing_bandwidth', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('compression', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('type_of_service', models.BooleanField(blank=True, default=False, null=True)),
                ('ipv6', models.BooleanField(blank=True, default=False, null=True)),
                ('pull_routes', models.BooleanField(blank=True, default=False, null=True)),
                ('add_remove_routes', models.BooleanField(blank=True, default=False, null=True)),
                ('verb', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('server_openvpn', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='openvpn.serveropenvpn')),
            ],
            options={
                'db_table': 'client_openvpn',
            },
        ),
    ]
