# Generated by Django 4.1.5 on 2023-07-11 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServerOpenvpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(default=0)),
                ('proto', models.CharField(default=None, max_length=10)),
                ('dev', models.CharField(default=None, max_length=10)),
                ('user', models.CharField(default=None, max_length=100)),
                ('group', models.CharField(default=None, max_length=100)),
                ('persist_key', models.CharField(default=None, max_length=100)),
                ('persist_tun', models.CharField(default=None, max_length=100)),
                ('keepalive', models.CharField(default=None, max_length=100)),
                ('topology', models.CharField(default=None, max_length=100)),
                ('server', models.CharField(default=None, max_length=100)),
                ('ifconfig_pool_persist', models.CharField(default=None, max_length=100)),
                ('server_ipv6', models.CharField(default=None, max_length=255)),
                ('tun_ipv6', models.CharField(default=None, max_length=255)),
                ('push_ipv4_option1', models.CharField(default=None, max_length=100)),
                ('push_ipv4_option2', models.CharField(default=None, max_length=100)),
                ('push_ipv4_option3', models.CharField(default=None, max_length=100)),
                ('dh', models.CharField(default=None, max_length=100)),
                ('ecdh_curve', models.CharField(default=None, max_length=100)),
                ('tls_crypt', models.CharField(default=None, max_length=100)),
                ('crl_verify', models.CharField(default=None, max_length=100)),
                ('ca', models.CharField(default=None, max_length=100)),
                ('cert', models.CharField(default=None, max_length=100)),
                ('key', models.CharField(default=None, max_length=100)),
                ('auth', models.CharField(default=None, max_length=100)),
                ('cipher', models.CharField(default=None, max_length=100)),
                ('ncp_ciphers', models.CharField(default=None, max_length=100)),
                ('tls_server', models.CharField(default=None, max_length=100)),
                ('tls_version_min', models.IntegerField(default=0)),
                ('tls_cipher', models.CharField(default=None, max_length=100)),
                ('client_config_dir', models.CharField(default=None, max_length=100)),
                ('status', models.CharField(default=None, max_length=100)),
                ('verb', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ClientOpenvpn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(default=None, max_length=255)),
                ('proto', models.CharField(default=None, max_length=10)),
                ('explicit_exit_notify', models.CharField(default=None, max_length=100)),
                ('remote', models.CharField(default=None, max_length=100)),
                ('dev', models.CharField(default=None, max_length=10)),
                ('resolv_retry', models.CharField(default=None, max_length=100)),
                ('nobind', models.CharField(default=None, max_length=100)),
                ('persist_key', models.CharField(default=None, max_length=100)),
                ('persist_tun', models.CharField(default=None, max_length=100)),
                ('remote_cert_tls', models.CharField(default=None, max_length=100)),
                ('verify_x509_name', models.CharField(default=None, max_length=100)),
                ('auth', models.CharField(default=None, max_length=100)),
                ('auth_nocache', models.CharField(default=None, max_length=100)),
                ('cipher', models.CharField(default=None, max_length=100)),
                ('tls_client', models.CharField(default=None, max_length=100)),
                ('tls_version_min', models.IntegerField(default=0)),
                ('tls_cipher', models.CharField(default=None, max_length=100)),
                ('ignore_unknown_option', models.CharField(default=None, max_length=100)),
                ('setenv', models.CharField(default=None, max_length=100)),
                ('verb', models.CharField(default=None, max_length=100)),
                ('ca_certificate', models.TextField(blank=True, default=None)),
                ('cert_certificate', models.TextField(blank=True, default=None)),
                ('private_key', models.TextField(blank=True, default=None)),
                ('tls_crypt', models.TextField(blank=True, default=None)),
                ('serverOpenvpn', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='openvpn.serveropenvpn')),
            ],
        ),
    ]
