# Generated by Django 4.1.5 on 2023-07-12 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveropenvpn',
            name='push_ipv6_option1',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='push_ipv6_option2',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='push_ipv6_option3',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='port',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='tls_version_min',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
