# Generated by Django 4.2.3 on 2023-08-15 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_ip6config_ipv4_connectivity_ip6config_ipv6_prefix_and_more'),
        ('openvpn', '0002_serveropenvpn_push_ipv6_option1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveropenvpn',
            name='interface',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='network.interface'),
        ),
    ]
