# Generated by Django 4.2.3 on 2023-08-16 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_ip6config_ipv4_connectivity_ip6config_ipv6_prefix_and_more'),
        ('openvpn', '0004_alter_serveropenvpn_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveropenvpn',
            name='compression',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='push_ipv4_option4',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='server_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='interface',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='network.interface'),
        ),
    ]
