# Generated by Django 4.2.3 on 2023-08-17 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_ip6config_ipv4_connectivity_ip6config_ipv6_prefix_and_more'),
        ('openvpn', '0005_serveropenvpn_compression_serveropenvpn_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveropenvpn',
            name='interface',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='network.interface'),
        ),
    ]
