# Generated by Django 4.2.3 on 2023-08-22 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_ip6config_ipv4_connectivity_ip6config_ipv6_prefix_and_more'),
        ('openvpn', '0006_alter_serveropenvpn_interface'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='serverOpenvpn',
        ),
        migrations.AddField(
            model_name='clientopenvpn',
            name='client_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientopenvpn',
            name='port',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='clientopenvpn',
            name='server_openvpn',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='openvpn.serveropenvpn'),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='auth',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='auth_nocache',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='ca_certificate',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='cert_certificate',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='cipher',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='dev',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='explicit_exit_notify',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='ignore_unknown_option',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='nobind',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='persist_key',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='persist_tun',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='private_key',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='proto',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='remote',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='remote_cert_tls',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='resolv_retry',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='setenv',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='tls_cipher',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='tls_client',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='tls_crypt',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='verb',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='verify_x509_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='interface',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='network.interface'),
        ),
    ]
