# Generated by Django 4.2.3 on 2023-08-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0007_remove_clientopenvpn_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientopenvpn',
            name='client_name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='server_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
