# Generated by Django 4.2.3 on 2023-08-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0008_alter_clientopenvpn_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveropenvpn',
            name='port',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, unique=True),
        ),
    ]
