# Generated by Django 4.2.3 on 2023-08-24 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0009_alter_serveropenvpn_port'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='clientopenvpn',
            table='ClientOpenvpn',
        ),
        migrations.AlterModelTable(
            name='serveropenvpn',
            table='ServerOpenvpn',
        ),
    ]
