# Generated by Django 4.2.3 on 2023-09-06 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0010_alter_clientopenvpn_table_alter_serveropenvpn_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveropenvpn',
            name='duplicate_connections',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='dynamic_ip',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='auth',
            field=models.CharField(blank=True, default='SHA256', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='cipher',
            field=models.CharField(blank=True, default='AES-256-CBC', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='dev',
            field=models.CharField(blank=True, default='tun', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='port',
            field=models.CharField(blank=True, default='1194', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='proto',
            field=models.CharField(blank=True, default='udp', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='topology',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='verb',
            field=models.CharField(blank=True, default='3', max_length=100, null=True),
        ),
    ]
