# Generated by Django 4.2.3 on 2023-09-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0011_serveropenvpn_duplicate_connections_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientopenvpn',
            old_name='client_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='serveropenvpn',
            old_name='server_name',
            new_name='name',
        ),
    ]
