# Generated by Django 4.2.3 on 2023-09-06 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0012_rename_client_name_clientopenvpn_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='ca_certificate',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='cert_certificate',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='private_key',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='compression',
        ),
        migrations.AddField(
            model_name='clientopenvpn',
            name='ca',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientopenvpn',
            name='cert',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientopenvpn',
            name='compression',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientopenvpn',
            name='description',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='clientopenvpn',
            name='key',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='duplicate_connections',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='dynamic_ip',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='interface',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='topology',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
