# Generated by Django 4.2.3 on 2023-09-07 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0013_remove_clientopenvpn_ca_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientopenvpn',
            name='resolv_retry',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
