# Generated by Django 4.2.3 on 2023-09-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0014_alter_clientopenvpn_resolv_retry'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientopenvpn',
            name='dh',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
