# Generated by Django 4.2.3 on 2023-09-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0015_clientopenvpn_dh'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientopenvpn',
            old_name='dh',
            new_name='ipv4_remote',
        ),
        migrations.RenameField(
            model_name='serveropenvpn',
            old_name='client_config_dir',
            new_name='compression',
        ),
        migrations.RenameField(
            model_name='serveropenvpn',
            old_name='crl_verify',
            new_name='dns_default_domain',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='remote',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='ecdh_curve',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='group',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='ifconfig_pool_persist',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='keepalive',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='ncp_ciphers',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='persist_key',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='persist_tun',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='push_ipv4_option1',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='push_ipv4_option2',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='push_ipv4_option3',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='push_ipv4_option4',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='push_ipv6_option1',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='push_ipv6_option2',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='push_ipv6_option3',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='server',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='server_ipv6',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='status',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='tls_cipher',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='tls_crypt',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='tls_server',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='tls_version_min',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='tun_ipv6',
        ),
        migrations.RemoveField(
            model_name='serveropenvpn',
            name='user',
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='force_dns_cache_update',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='gateway',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='hardware_crypto',
            field=models.CharField(blank=True, default='No Hardware Crypto', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='inter_clients',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='ipv6',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='type_of_service',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
