# Generated by Django 4.2.3 on 2023-09-08 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0016_rename_dh_clientopenvpn_ipv4_remote_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='auth_nocache',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='explicit_exit_notify',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='ignore_unknown_option',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='nobind',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='persist_key',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='persist_tun',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='remote_cert_tls',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='setenv',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='tls_cipher',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='tls_client',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='tls_crypt',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='tls_version_min',
        ),
        migrations.RemoveField(
            model_name='clientopenvpn',
            name='verify_x509_name',
        ),
    ]
