# Generated by Django 4.2.3 on 2023-09-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0017_remove_clientopenvpn_auth_nocache_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientopenvpn',
            name='hardware_crypto',
            field=models.CharField(blank=True, default='No Hardware Crypto', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientopenvpn',
            name='interface',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clientopenvpn',
            name='ipv6',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='clientopenvpn',
            name='type_of_service',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='port',
            field=models.CharField(blank=True, default='1194', max_length=10, null=True, unique=True),
        ),
    ]
