# Generated by Django 4.2.3 on 2023-09-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0018_clientopenvpn_hardware_crypto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientopenvpn',
            name='secret',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='dns_server1',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='dns_server2',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='ipv4_local_network',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='ipv4_remote_network',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='ntp_server1',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='ntp_server2',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='secret',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='ca',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='cert',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clientopenvpn',
            name='key',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='ca',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='cert',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='key',
            field=models.CharField(blank=True, default=None, max_length=300, null=True),
        ),
    ]
