# Generated by Django 4.2.3 on 2023-09-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0020_alter_serveropenvpn_interface'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveropenvpn',
            name='bridge_end_dhcp',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='bridge_interface',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serveropenvpn',
            name='bridge_start_dhcp',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='serveropenvpn',
            name='interface',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
