# Generated by Django 4.1.5 on 2024-06-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipsecmonitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipsecmonitoring',
            name='total_bytes',
            field=models.IntegerField(null=True),
        ),
    ]
