# Generated by Django 4.1.5 on 2024-01-16 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('members', models.CharField(blank=True, default=None, max_length=1000)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='SdwanRules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('source_address', models.CharField(blank=True, default=None, max_length=250, unique=True)),
                ('algorythme_type', models.CharField(blank=True, default=None, max_length=100)),
                ('destination_address', models.CharField(blank=True, default=None, max_length=200)),
                ('health_check', models.CharField(blank=True, default=None, max_length=200)),
                ('health_check_target', models.CharField(blank=True, default=None, max_length=200)),
                ('primary_interface', models.CharField(blank=True, default=None, max_length=200)),
                ('area', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sdwan.area')),
            ],
            options={
                'db_table': 'sdwan_rules',
            },
        ),
    ]
