# Generated by Django 4.1.5 on 2024-03-09 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gateway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_address', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=1000, null=True)),
                ('gateway', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='gateway.gateway')),
            ],
            options={
                'db_table': 'routing',
            },
        ),
    ]
