# Generated by Django 4.1.5 on 2024-10-29 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gateway', '0001_initial'),
        ('routing', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routing',
            unique_together={('destination_address', 'gateway')},
        ),
    ]
