# Generated by Django 4.1.5 on 2025-04-08 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_alter_interface_description'),
        ('routing', '0002_alter_routing_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='routing',
            name='interface',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='network.interface'),
        ),
    ]
