# Generated by Django 4.2.7 on 2023-12-15 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyuser',
            name='email',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
