# Generated by Django 4.1.5 on 2024-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0008_accesslogs_cachelogs_storelogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proxyuser',
            name='username',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='username'),
        ),
    ]
