# Generated by Django 4.2.1 on 2023-06-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InboundRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=200, null=True)),
                ('rule_status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'InboundRule',
            },
        ),
    ]
