# Generated by Django 4.1.5 on 2023-10-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_tempsexucution_interface_description_and_more'),
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=200, null=True, unique=True)),
                ('rule_status', models.BooleanField(default=False)),
                ('type_rule', models.CharField(max_length=200, null=True)),
                ('policy', models.CharField(max_length=200, null=True)),
                ('rule_description', models.CharField(max_length=200, null=True)),
                ('protocol', models.CharField(max_length=200, null=True)),
                ('saddr', models.CharField(max_length=200, null=True)),
                ('sport', models.IntegerField(null=True)),
                ('daddr', models.CharField(max_length=200, null=True)),
                ('dport', models.IntegerField(null=True)),
                ('interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'rule',
            },
        ),
        migrations.DeleteModel(
            name='InboundRule',
        ),
    ]
