# Generated by Django 4.2.1 on 2023-06-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0003_inboundrule_type_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboundrule',
            name='type_rule',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
