# Generated by Django 4.2.1 on 2023-07-03 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
        ('rules', '0004_alter_inboundrule_type_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', models.CharField(max_length=200, null=True, unique=True)),
                ('rule_status', models.BooleanField(default=False)),
                ('type_rule', models.CharField(max_length=200, null=True)),
                ('policy', models.CharField(max_length=200, null=True)),
                ('Rule_description', models.CharField(max_length=200, null=True)),
                ('protocol', models.CharField(max_length=200, null=True)),
                ('source', models.CharField(max_length=200, null=True)),
                ('src_port', models.IntegerField(null=True)),
                ('destination', models.CharField(max_length=200, null=True)),
                ('dst_port', models.IntegerField(null=True)),
                ('interface', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='network.interface')),
            ],
            options={
                'db_table': 'Rule',
            },
        ),
        migrations.DeleteModel(
            name='InboundRule',
        ),
    ]
