# Generated by Django 4.2.1 on 2023-07-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0005_rule_delete_inboundrule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='destination',
            new_name='daddr',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='dst_port',
            new_name='dport',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='source',
            new_name='saddr',
        ),
        migrations.RenameField(
            model_name='rule',
            old_name='src_port',
            new_name='sport',
        ),
    ]
