# Generated by Django 4.1.5 on 2023-01-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementGroup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='gid',
        ),
        migrations.AlterModelTable(
            name='group',
            table='Group',
        ),
    ]
