# Generated by Django 4.1.5 on 2023-01-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementGroup', '0002_remove_group_gid_alter_group_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='gid',
            field=models.IntegerField(null=True),
        ),
    ]
