# Generated by Django 4.1.5 on 2023-02-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementGroup', '0003_group_gid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='gid',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupname',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
