# Generated by Django 4.1.5 on 2023-02-06 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementGroup', '0004_alter_group_gid_alter_group_groupname'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created_by_system',
            field=models.BooleanField(default=False),
        ),
    ]
