# Generated by Django 5.1.4 on 2025-02-03 08:53

import backend.vxlan.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vxlan', '0007_alter_vxlan_vxlan_connection_uuid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vxlan',
            name='vxlan_destination_address',
            field=models.GenericIPAddressField(verbose_name='destination address'),
        ),
        migrations.AlterField(
            model_name='vxlan',
            name='vxlan_destination_port',
            field=models.CharField(max_length=5, validators=[backend.vxlan.models.validate_port], verbose_name='port'),
        ),
        migrations.AlterField(
            model_name='vxlan',
            name='vxlan_source_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='source address'),
        ),
    ]
