# Generated by Django 4.1.5 on 2024-08-26 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementLogs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogrotateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=200)),
                ('filename', models.CharField(blank=True, max_length=200, unique=True)),
                ('original_path', models.CharField(blank=True, max_length=200)),
                ('backup_path', models.CharField(blank=True, max_length=200)),
                ('date', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'db_table': 'logrotate_data',
            },
        ),
    ]
