# Generated by Django 4.1.5 on 2024-09-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_interface_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
