# Generated by Django 4.1.5 on 2024-04-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0006_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
