# Generated by Django 4.1.5 on 2025-04-28 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0018_alter_roles_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roles',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
