# Generated by Django 4.2.7 on 2023-12-25 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0002_proxyuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxyrules',
            name='days',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='proxyrules',
            name='time_from',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='proxyrules',
            name='tome_to',
            field=models.TimeField(null=True),
        ),
    ]
