# Generated by Django 4.2.7 on 2024-01-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proxy', '0004_rename_tome_to_proxyrules_time_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerSatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'server_status',
            },
        ),
    ]
