# Generated by Django 4.1.5 on 2024-02-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ids_ips', '0007_alter_suricatainterface_copy_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='suricatafile',
            name='mode_inline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
