# Generated by Django 4.1.5 on 2024-03-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='vlan_priority',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='vlan_tag',
            field=models.IntegerField(unique=True),
        ),
    ]
