# Generated by Django 4.1.5 on 2024-03-05 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlan', '0002_alter_vlan_vlan_priority_alter_vlan_vlan_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='description',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
