# Generated by Django 4.1.5 on 2024-03-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlan', '0003_alter_vlan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='vlan_priority',
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
    ]
