# Generated by Django 4.1.5 on 2024-10-22 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlan', '0006_alter_vlan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
