# Generated by Django 4.1.5 on 2024-12-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlan', '0007_alter_vlan_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='vlan_priority',
            field=models.CharField(max_length=200, null=True, verbose_name='priority'),
        ),
        migrations.AlterField(
            model_name='vlan',
            name='vlan_tag',
            field=models.IntegerField(unique=True, verbose_name='tag'),
        ),
    ]
