# Generated by Django 4.1.5 on 2024-03-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nat', '0005_dnat_prerouting_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnat',
            name='dnat_position',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='onetoonenat',
            name='one_to_one_nat_position',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='snat',
            name='snat_position',
            field=models.IntegerField(default=None, null=True, unique=True),
        ),
    ]
