# Generated by Django 4.1.5 on 2024-12-19 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vxlan', '0005_alter_vxlan_vxlan_interface_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vxlan',
            name='vxlan_interface_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
