# Generated by Django 4.1.5 on 2023-01-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementGroup', '0002_remove_group_gid_alter_group_table'),
        ('managementUsers', '0002_alter_user_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.AddField(
            model_name='user',
            name='group',
            field=models.ManyToManyField(to='managementGroup.group'),
        ),
    ]
