# Generated by Django 4.1.5 on 2023-01-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0003_delete_group_user_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('context', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.ManyToManyField(to='managementUsers.permission'),
        ),
    ]
