# Generated by Django 4.1.5 on 2023-01-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0004_permission_user_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(max_length=800, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
