# Generated by Django 4.1.5 on 2023-02-06 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0006_alter_user_uid_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by_system',
            field=models.BooleanField(default=True),
        ),
    ]
