# Generated by Django 4.1.5 on 2023-02-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0007_user_createdbysystem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='createdBySystem',
            field=models.BooleanField(default=False),
        ),
    ]
