# Generated by Django 4.1.5 on 2023-02-06 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0008_alter_user_createdbysystem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='createdBySystem',
        ),
    ]
