# Generated by Django 4.1.5 on 2023-03-06 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0012_alter_user_managers_remove_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_auth',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
