# Generated by Django 4.1.5 on 2023-03-06 10:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0013_user_token_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='token_last_expired',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
