# Generated by Django 4.1.5 on 2023-03-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0014_user_token_last_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token_last_expired',
            field=models.DateTimeField(),
        ),
    ]
