# Generated by Django 4.1.5 on 2023-03-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0016_alter_user_token_last_expired'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='token_auth',
        ),
    ]
