# Generated by Django 4.1.5 on 2023-09-08 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managementUsers', '0018_user_is_verified_user_organisation'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
