# Generated by Django 5.1.4 on 2025-02-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlan', '0008_alter_vlan_description_alter_vlan_vlan_priority_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='vlan_priority',
            field=models.CharField(choices=[('Best Effort ( 0 , default )', 'Best Effort ( 0 , default )'), ('Background ( 1, lowest)', 'Background ( 1, lowest)'), ('Excellent Effort (2)', 'Excellent Effort (2)'), ('Critical Applications (3)', 'Critical Applications (3)'), ('Video (4)', 'Video (4)'), ('Voice (5)', 'Voice (5)'), ('Internetwork Control (6)', 'Internetwork Control (6)'), ('Network Control (7)', 'Network Control (7)')], max_length=200, null=True, verbose_name='priority'),
        ),
    ]
