# Generated by Django 4.1.5 on 2024-12-25 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managementLogs', '0002_logrotatedata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logrotatedata',
            name='filename',
            field=models.CharField(blank=True, max_length=200, unique=True, verbose_name='file name'),
        ),
    ]
